### ISSUE TITLE
BOT - Using #!stats has unwanted behaviors

### ISSUE THREAD

**Issue by RDardelet** [DiscordDungeons/Bugs#10]
Should be set to high priority.

Using the ``#!stats <@username>`` command in private message will show the following error:
```errorlog
TypeError: Cannot read property 'roles' of undefined
    at Object.defaults.stats.process (/root/RPGBot/cmds/defaults.js:2632:35)
    at Client.<anonymous> (/root/RPGBot/main.js:780:23)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at WebSocket.websocket.onmessage (/root/RPGBot/node_modules/discord.js/lib/Client/InternalClient.js:1982:16)
    at WebSocket.onMessage (/root/RPGBot/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/root/RPGBot/node_modules/ws/lib/WebSocket.js:841:10)
    at /root/RPGBot/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/root/RPGBot/node_modules/ws/lib/Receiver.js:371:5)
    at /root/RPGBot/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/root/RPGBot/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.opcodes.1.finish (/root/RPGBot/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/root/RPGBot/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/root/RPGBot/node_modules/ws/lib/Receiver.js:103:24)
```

The ``#!stats <@username>`` command in the DRPG server triggers a change of role and resets the user's nickname to fit the guild of the corresponding ``<@username>`` mention.

Tested on Discord Desktop Windows

**Comment by Sven65** [comment]
Fixed it yesterday.
