### ISSUE TITLE
CAN'T TALK TO NPC

### ISSUE THREAD

**Issue by Jackson1324** [DiscordDungeons/Bugs#1001]
Just can't talk to NPC

**To Reproduce**
1. Go to any location that have an NPC
2. type #!talk <NPC name>
3. this:
Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'current' of null
    at Talk._prepareDialog (/home/mackan/RPGBot/src/Commands/Commands/Locations/Talk.js:848:34)
    at async Talk.Execute (/home/mackan/RPGBot/src/Commands/Commands/Locations/Talk.js:922:18)
**Screenshots**
![image](https://user-images.githubusercontent.com/83914779/117577224-23ea8880-b113-11eb-9ebc-e2320274616e.png)

**Comment by Sven65** [comment]
Hi! This issue is most likely due to you having user data from before we added locations, to verify, check if you can use the `#!location` command. If it gives you an error similar to this one, you don't have the location data, and you'll need to contact me on Discord in order for me to resolve it for you.

**Comment by Jackson1324** [comment]
i did have the user date before the update, but i can use the location command normally 
![image](https://user-images.githubusercontent.com/83914779/117658948-89974d00-b1c5-11eb-8aa8-8b287bc05dfc.png)

**Comment by Sven65** [comment]
Thanks, your stats are indeed lacking the location property, atleast by the output of the `location` command. I'll be contacting you on Discord for further assistance.

**Comment by Sven65** [comment]
To do: add a check for if the user has the property or not
