### ISSUE TITLE
Dialog reaction error?

### ISSUE THREAD

**Issue by Rain247fire** [DiscordDungeons/Bugs#1019]
Whoops. An error occured. Please report this in the official server.
DiscordAPIError: Unknown Message
    at RequestHandler.execute (/home/mackan/RPGBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/mackan/RPGBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)

**Comment by Rain247fire** [comment]
I think it might be coming from the monk puzzle (quest: a small task).
