### ISSUE TITLE
no null check for member

### ISSUE THREAD

**Issue by towstone** [DiscordDungeons/Bugs#1022]
Received this error:
TypeError: Cannot read property 'member' of null
    at FickleFishing._getAuthor (/home/mackan/RPGBot/src/Data/Quest/Quest.js:188:27)
    at FickleFishing.optionDialog (/home/mackan/RPGBot/src/Data/Quest/Quest.js:242:30)
    at /home/mackan/RPGBot/src/Data/Quest/Quests/FickleFishing.js:78:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**To Reproduce**
Somewhat New user
Stop Tutorial quest with out completing
talk to Angler Dave
Select 1 to get details of new job

**Expected behavior**
Not receive a programming error

**Version**
DRPG Version 4.15.7

**Comment by towstone** [comment]
Per sugestion
Manhuntwastaken [Lvl. 119]
 — 
Today at 3:26 PM
“#!quest”, react with 3

still receiving
'''
TypeError: Cannot read property 'member' of null
    at FickleFishing._getAuthor (/home/mackan/RPGBot/src/Data/Quest/Quest.js:188:27)
    at FickleFishing.optionDialog (/home/mackan/RPGBot/src/Data/Quest/Quest.js:242:30)
    at /home/mackan/RPGBot/src/Data/Quest/Quests/FickleFishing.js:78:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
'''

**Comment by towstone** [comment]
Looks like this should have a user error message like "Quests only available on Discord Dungeon server." or "Quests may not be available outside the Discord Dungeon server."
