### ISSUE TITLE
#!adventure bug

### ISSUE THREAD

**Issue by SoxxZ** [DiscordDungeons/Bugs#105]
```js
TypeError: Cannot read property 'length' of undefined
    at Adventure.get.then (/home/Mackan/RPGBot/src/Commands/adventure/adventure.js:292:20)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

i solved with an #!reset, but i'm reporting for future issues like this.

**Comment by Sven65** [comment]
Added syntax highlighting.

Are you an older player? As in, did you get your stats before three months ago?

**Comment by SoxxZ** [comment]
yes, i'm an older player.Yes.

**Comment by Sven65** [comment]
Then that's the issue. I'll be adding a hotfix in the coming week and close the issue.
