### ISSUE TITLE
🐛 Bug Report: Planting doesn't work

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1060]
### 👟 Reproduction steps

Buy a field
`#+plant set carrot seed`

### 👍 Expected behavior

some confirmation message about planting working

### 👎 Actual Behavior

``` TypeError: Cannot set properties of undefined (setting '1')
    at Plant.setPlant (/bin/src/Commands/Commands/Sides/Plant.ts:70:51)
    at Plant.execute (/bin/src/Commands/Commands/Sides/Plant.ts:324:16)

### 🎲 DRPG version

16.4.13-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

_No response_

**Comment by Sven65** [comment]
Fixed.
