### ISSUE TITLE
#!gbbuy  bug

### ISSUE THREAD

**Issue by DatKawaiiGuy** [DiscordDungeons/Bugs#110]
Tried to buy a single health potion, this was the result

Whoops. An error occured. Please report this in the official server.
```js
TypeError: Cannot read property 'length' of undefined
    at BitapSearcher.search (/home/Mackan/RPGBot/node_modules/fuse.js/src/fuse.js:642:58)
    at Fuse._analyze (/home/Mackan/RPGBot/node_modules/fuse.js/src/fuse.js:281:43)
    at Fuse._analyze (/home/Mackan/RPGBot/node_modules/fuse.js/src/fuse.js:324:14)
    at Fuse._startSearch (/home/Mackan/RPGBot/node_modules/fuse.js/src/fuse.js:198:16)
    at Fuse.search (/home/Mackan/RPGBot/node_modules/fuse.js/src/fuse.js:129:10)
    at Items.getAll.then (/home/Mackan/RPGBot/src/Commands/market/gbbuy.js:72:30)
```

**Comment by Sven65** [comment]
Changed it to have syntax highlighting

**Comment by Sven65** [comment]
How do I reproduce the issue?

**Comment by Sven65** [comment]
Unable to reproduce.
