### ISSUE TITLE
🐛 Bug Report: checking a really old planted seed

### ISSUE THREAD

**Issue by thejawesomeone** [DiscordDungeons/Bugs#1132]
### 👟 Reproduction steps

Checked a plant in Copperfall that I had set over 2 years ago

### 👍 Expected behavior

Have harvested the plant and given me wheat, as that was the planted seed

### 👎 Actual Behavior

TypeError: saplingTime.toString(...).timeSince is not a function
    at Plant.checkPlant (/bin/src/Commands/Commands/Sides/Plant.ts:257:135)
    at Plant.execute (/bin/src/Commands/Commands/Sides/Plant.ts:341:5)

immediately posted that and recommended that I post this bug report

### 🎲 DRPG version

4.17.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Not really, just haven't played the game for a really long time

**Comment by thejawesomeone** [comment]
Good news, doing that did remove the old seed so at least I can still use that planting spot, put a grape seed there :)
