### ISSUE TITLE
🐛 Bug Report: Deadlock error???

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1136]
### 👟 Reproduction steps

idk how to reproduce, all it was is general commands being used caused it

### 👍 Expected behavior

idk for the error not to show?

### 👎 Actual Behavior

```
QueryFailedError: deadlock detected
    at QueryFailedError.TypeORMError [as constructor] (/bin/rpgbot/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/bin/rpgbot/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/bin/rpgbot/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Edited //
Few message links of where it been happening,
[1.....](https://discord.com/channels/172382467385196544/172388282057883648/913679717759062067)
[2.....](https://discord.com/channels/172382467385196544/172388244007288832/913616040393572383)
[3.....](https://discord.com/channels/172382467385196544/172388304992468992/913485791953584228)
[4.....](https://discord.com/channels/172382467385196544/172388304992468992/913337499651297312)
[5.....](https://discord.com/channels/172382467385196544/172388282057883648/910011519335563274)

### 🎲 DRPG version

4.17.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
https://github.com/typeorm/typeorm/issues/5129
https://www.cybertec-postgresql.com/en/postgresql-understanding-deadlocks/

@Sven65 May help to have some server logs from when this error happens?

**Comment by Sven65** [comment]
This is a weird issue, I'll give it a look.

> Might be relevant: [typeorm/typeorm#5129](https://github.com/typeorm/typeorm/issues/5129) https://www.cybertec-postgresql.com/en/postgresql-understanding-deadlocks/
> 
> @Sven65 May help to have some server logs from when this error happens?

I'm unable to provide server logs relating to the database.

**Comment by mount2010** [comment]
Sorry, I meant it might help to look through the logs for incidents of this error.

**Comment by Sven65** [comment]
I've been unable to reproduce this error and I haven't seen it in the slash command rewrite.

If the issue still occurs, please reopen.
