### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by kiotashma** [DiscordDungeons/Bugs#1137]
### 👟 Reproduction steps

when i was continuing doing the usual commands #!adv and the sides it didnt reply for about 5-10 seconds and started sending about 6 messages saying theres a bug

### 👍 Expected behavior

it would normally send the orignal message of adv and the sides

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/94707145/142667844-60b18178-f2a7-4087-bbec-ba22b43755c1.png)

### 🎲 DRPG version

4.17.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

QueryFailedError: deadlock detected
    at QueryFailedError.TypeORMError [as constructor] (/bin/rpgbot/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/bin/rpgbot/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/bin/rpgbot/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by FelixArgyle** [comment]
Already been reported,
#https://github.com/DiscordDungeons/Bugs/issues/1136
