### ISSUE TITLE
Mining Bug or Queue Error(threading?)

### ISSUE THREAD

**Issue by echagen22** [DiscordDungeons/Bugs#1175]
https://discord.com/channels/172382467385196544/256422035570425856/939161415657357362

**Comment by Sven65** [comment]
Hi, please use the template or form when creating a bug report.

**Comment by Sven65** [comment]
After checking the link, the error is

```ts
QueryFailedError: deadlock detected
    at QueryFailedError.TypeORMError [as constructor] (/bin/rpgbot/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/bin/rpgbot/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/bin/rpgbot/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

and is the same as #1136
