### ISSUE TITLE
Zinc Tools Uncreatable

### ISSUE THREAD

**Issue by SpringerBrandon** [DiscordDungeons/Bugs#1186]
.craft zinc axe
Dungeon Master
BOT
 — Today at 1:47 AM
Whoops. An error occured.
To report it, go to the link in .bug, or visit .serverinvite for support.
ReqlDriverError: The connection was closed by the other party.
    at Connection._send (/bin/rpgbot/node_modules/rethinkdbdash/lib/connection.js:724:15)
    at /bin/rpgbot/node_modules/rethinkdbdash/lib/term.js:202:22
    at tryCatcher (/bin/rpgbot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/bin/rpgbot/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/bin/rpgbot/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/bin/rpgbot/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/bin/rpgbot/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/bin/rpgbot/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/bin/rpgbot/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/bin/rpgbot/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
Kelevrax used 2 Willow Logs, 3 Zinc Ingots, a Copper Axe and a Oak Log to make a Zinc Axe.

**Comment by SpringerBrandon** [comment]
.craft zinc shears
Dungeon Master
BOT
 — Today at 1:51 AM
Whoops. An error occured.
To report it, go to the link in .bug, or visit .serverinvite for support.
ReqlDriverError: The connection was closed by the other party.
    at Connection._send (/bin/rpgbot/node_modules/rethinkdbdash/lib/connection.js:724:15)
    at /bin/rpgbot/node_modules/rethinkdbdash/lib/term.js:202:22
    at tryCatcher (/bin/rpgbot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/bin/rpgbot/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/bin/rpgbot/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/bin/rpgbot/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/bin/rpgbot/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/bin/rpgbot/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/bin/rpgbot/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/bin/rpgbot/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
Kelevrax used 3 Zinc Ingots, a Oak Log, a Willow Log and a pair of Copper Shears to make a pair of Zinc Shears.

**Comment by SpringerBrandon** [comment]
.craft zinc fishing rod
Dungeon Master
BOT
 — Today at 1:59 AM
Whoops. An error occured.
To report it, go to the link in .bug, or visit .serverinvite for support.
ReqlDriverError: The connection was closed by the other party.
    at Connection._send (/bin/rpgbot/node_modules/rethinkdbdash/lib/connection.js:724:15)
    at /bin/rpgbot/node_modules/rethinkdbdash/lib/term.js:202:22
    at tryCatcher (/bin/rpgbot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/bin/rpgbot/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/bin/rpgbot/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/bin/rpgbot/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/bin/rpgbot/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/bin/rpgbot/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/bin/rpgbot/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/bin/rpgbot/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
Kelevrax used 3 Zinc Ingots, a Copper Fishing Rod, a Oak Log and a Willow Log to make a Zinc Fishing Rod.

**Comment by Sven65** [comment]
Hi! You don't need to post the same error message multiple times as it's the same command :)

**Comment by Sven65** [comment]
No problem! This should be fixed now, apologies for the late reply.
