### ISSUE TITLE
Deadlock detected 

### ISSUE THREAD

**Issue by JaggerSofia** [DiscordDungeons/Bugs#1188]
There have been lag when I use the skills command so they all come through after I've typed all of them out. All of the skills do go through, as well as this error message popping up.

QueryFailedError: deadlock detected
    at QueryFailedError.TypeORMError [as constructor] (/bin/rpgbot/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/bin/rpgbot/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/bin/rpgbot/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by FelixArgyle** [comment]
Already reported, please make sure to take the time to find if the error has already been reported ++ in future follow the bug report [Template](https://github.com/DiscordDungeons/Bugs/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%F0%9F%90%9B+Bug+Report%3A+)
