### ISSUE TITLE
#!lead issue

### ISSUE THREAD

**Issue by Knaffils** [DiscordDungeons/Bugs#119]
Hey there, I found an issue with the #!lead command. 

This is what I got when I typed it in.

ReqlResourceLimitError: Array over size limit `100000` in:
r.table("users").orderBy(r.desc(r.row("level"))).limit(15).pluck(["level"], "id", "name").default(null)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       
    at ReqlResourceLimitError.ReqlError [as constructor] (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:23:13)
    at ReqlResourceLimitError.ReqlRuntimeError [as constructor] (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:90:51)
    at new ReqlResourceLimitError (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:123:57)
    at mkErr (/home/Mackan/RPGBot/node_modules/rethinkdb/util.js:177:10)
    at TcpConnection.Connection._processResponse (/home/Mackan/RPGBot/node_modules/rethinkdb/net.js:152:16)
    at TcpConnection.Connection._data (/home/Mackan/RPGBot/node_modules/rethinkdb/net.js:122:12)
    at Socket.<anonymous> (/home/Mackan/RPGBot/node_modules/rethinkdb/net.js:689:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

Hope I could help. :)

**Comment by Sven65** [comment]
We are aware of the issue at hand, though we are unable to fix it at the current point due to the topic needing more research.

**Comment by Zashino** [comment]
Yo, this should be fixed if you add an index on the level row
[other rethinkdb users have that issue too](https://github.com/rethinkdb/rethinkdb/issues/2303)

**Comment by Sven65** [comment]
Fixed.
