### ISSUE TITLE
🐛 Bug Report: QueryFailedError: deadlock detected

### ISSUE THREAD

**Issue by BuoYancYdabl** [DiscordDungeons/Bugs#1191]
### 👟 Reproduction steps

I don't know why that happend. I've seen this only once, so: travel from Silverkeep to Mournstead, try to forage after inbound but have cooldown and then try to #!adv. Exactly #!adv threw this error.
UPD: #!travel mournstead/silverkeep (between those), after traveling right when message appear try do stuff (adventures, sides). 50/50 you can catch error.

### 👍 Expected behavior

Usual adventure display and behavior, sides activity

### 👎 Actual Behavior

Errors. Lots of errors

### 💥 Error message

QueryFailedError: deadlock detected
    at QueryFailedError.TypeORMError [as constructor] (/bin/rpgbot/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/bin/rpgbot/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/bin/rpgbot/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### 🎲 DRPG version

4.17.20

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

After that error bot works properly. This is rare (no, it is often) error.

UPD: also cathed that same error when traveled from silverkeep to mournstead and tried to #!fish. I think it's somehow linked to traveling. Deadlock is usually something else than error says. Try to look in traveling func's.

PS UPD: happend already 7 times. Once 2 times in a row and 1 after 20 seconds. Everything is happening right after traveling silverkeep or mournstead and doing sides or adventure!

**Comment by FelixArgyle** [comment]
Already reported + Issue is known for what makes it happen, #1136 
please make sure to check that if an issue has been reported since you checked the box.
