### ISSUE TITLE
🐛 Bug Report: [BETA] pet set name error

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1195]
### 👟 Reproduction steps

/pet set option:name value:waifu

### 👍 Expected behavior

for it to set the name to the given input a user puts

### 👎 Actual Behavior

errors with error below

### 💥 Error message

```
TypeError: Cannot read properties of undefined (reading 'nameBlacklist')
    at setName (/bin/src/SlashCommands/Commands/Pets/PetSet.ts:90:37)
    at PetSet.run (/bin/src/SlashCommands/Commands/Pets/PetSet.ts:227:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PetCommand.routeToSubcommands (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:48:10)
    at PetCommand.run (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:73:10)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:663:28)
```

### 🎲 DRPG version

v4.18.1-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
