### ISSUE TITLE
🐛 Bug Report: [BETA] guild blacklist add

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1196]
### 👟 Reproduction steps

/g blacklist add user: @Crusch Karsten (felix69)

### 👍 Expected behavior

for it to add user to blacklist 

### 👎 Actual Behavior

errors with thing below

### 💥 Error message

```
Error: Couldn't find a subcommand that handles the subcommand string blacklist add. Please inform a developer!
    at GuildCommand.routeToSubcommands (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:47:26)
    at GuildCommand.run (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:73:21)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:661:37)
    at SlashCreator._onInteraction (/bin/rpgbot/node_modules/slash-create/lib/creator.js:581:33)
    at /bin/rpgbot/node_modules/slash-create/lib/creator.js:196:65
    at WebSocketManager.<anonymous> (/bin/src/Bot.ts:145:2)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### 🎲 DRPG version

v4.18.1-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
