### ISSUE TITLE
🐛 Bug Report: [BETA[ Trap Check no worky

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1202]
### 👟 Reproduction steps

/trap check
(in trap spot location with a current trap set)

I HAVE MIGRATED DATA SO THAT MIGHT BE SOMETHING?

### 👍 Expected behavior

For it to check your trap normally / give the items etc

### 👎 Actual Behavior

error error

### 💥 Error message

```
TypeError: Cannot read properties of undefined (reading 'trap')
    at TrapCheckCommand.getTrapResults (/bin/src/SlashCommands/Commands/Sides/Trap/TrapCheck.ts:102:40)
    at TrapCheckCommand.checkTrap (/bin/src/SlashCommands/Commands/Sides/Trap/TrapCheck.ts:161:10)
    at TrapCheckCommand.run (/bin/src/SlashCommands/Commands/Sides/Trap/TrapCheck.ts:178:10)
    at TrapCommand.routeToSubcommands (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:53:10)
    at TrapCommand.run (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:78:10)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:663:28)
```

### 🎲 DRPG version

v4.18.2-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed.
