### ISSUE TITLE
🐛 Bug Report: [BETA] quest completed

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1213]
### 👟 Reproduction steps

/quest show-completed

### 👍 Expected behavior

for it to show the quests i've completed

--- I HAVE MIGRATED DATA IF THAT IS ANYTHING

### 👎 Actual Behavior

error error 

### 💥 Error message

```
TypeError: Cannot read properties of undefined (reading 'name')
    at /bin/src/SlashCommands/Commands/User/Quest.ts:74:25
    at Array.forEach (<anonymous>)
    at QuestCommand.showCompleted (/bin/src/SlashCommands/Commands/User/Quest.ts:72:30)
    at QuestCommand.run (/bin/src/SlashCommands/Commands/User/Quest.ts:169:23)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:663:28)
```

### 🎲 DRPG version

v4.18.2-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed.
