### ISSUE TITLE
🐛 Bug Report: [BETA] Market sell/buy

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1223]
### 👟 Reproduction steps

/m buy offer: ku5gs559

Buy / Sell to a trade that the user has their dm's turned off /or not in any mutual servers with the bot

### 👍 Expected behavior

For it to just continue with the normal buy/sell message but just not dm the user if they don't share a server / have dm's turned off

### 👎 Actual Behavior

errors due to user not having dm turned on / not sharing mutual server with the bot

### 💥 Error message

```
DiscordAPIError: Cannot send messages to this user
    at RequestHandler.execute (/bin/rpgbot/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RequestHandler.push (/bin/rpgbot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at DMChannel.send (/bin/rpgbot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:171:15)
    at MBuy.run (/bin/src/SlashCommands/Commands/Market/MCommand/MBuy.ts:108:5)
    at MCommand.routeToSubcommands (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:53:10)
    at MCommand.run (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:78:10)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:663:28)
```

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
