### ISSUE TITLE
🐛 Bug Report: [BETA] TP Command

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1224]
### 👟 Reproduction steps

/tp location: (anything that isn't a matching thing)
error

### 👍 Expected behavior

for it to have some message saying "this is not a valid location, user

### 👎 Actual Behavior

error

### 💥 Error message

```
TypeError: Cannot read properties of undefined (reading 'name')
    at TPCommand.run (/bin/src/SlashCommands/Commands/Admin/Tp.ts:56:57)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:663:28)
```

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
