### ISSUE TITLE
Error when running !lead

### ISSUE THREAD

**Issue by oolivero45** [DiscordDungeons/Bugs#123]
When I run !lead, I get the following error:

ReqlResourceLimitError: Array over size limit `100000` in:
r.table("users").orderBy(r.desc(r.row("level"))).limit(15).pluck(["level"], "id", "name").default(null)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       
    at ReqlResourceLimitError.ReqlError [as constructor] (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:23:13)
    at ReqlResourceLimitError.ReqlRuntimeError [as constructor] (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:90:51)
    at new ReqlResourceLimitError (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:123:57)
    at mkErr (/home/Mackan/RPGBot/node_modules/rethinkdb/util.js:177:10)
    at TcpConnection.Connection._processResponse (/home/Mackan/RPGBot/node_modules/rethinkdb/net.js:152:16)
    at TcpConnection.Connection._data (/home/Mackan/RPGBot/node_modules/rethinkdb/net.js:122:12)
    at Socket.<anonymous> (/home/Mackan/RPGBot/node_modules/rethinkdb/net.js:689:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by PlayTheFallen** [comment]
#119

**Comment by Sven65** [comment]
As @PlayTheFallen said, see #119
