### ISSUE TITLE
🐛 Bug Report: [BETA] Namazu quest

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1230]
### 👟 Reproduction steps

Get to the stage where you gotta give items, mushroom, lychee and carrot to tobin,
after getting to the part after giving it to them
```
!====[Crusch Karsten (felix69)'s conversation]====!
Tobin - Aah! Everyone run, an earthquake is starting— I should have known, it’s Namazu the Earthshaker! Adventurer, save us!
!=================================================!
```
it errors after that message is sent

### 👍 Expected behavior

for quest to proceed without the error

### 👎 Actual Behavior

quest errors at step mentioned in reproduction

### 💥 Error message

```
Error: Fetch your original message or use deferred messages before registering components
    at CommandContext.registerComponent (/bin/rpgbot/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:224:19)
    at /bin/src/Data/Quest/Quest.ts:497:9
    at new Promise (<anonymous>)
    at NamazuQuest.continueCheckMessage (/bin/src/Data/Quest/Quest.ts:482:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at NamazuQuest.handleStage (/bin/src/Data/Quest/Quests/NamazuQuest.ts:122:24)
    at TalkCommand.handleQuest (/bin/src/SlashCommands/Commands/Location/Talk.ts:646:6)
    at TalkCommand.run (/bin/src/SlashCommands/Commands/Location/Talk.ts:897:18)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:663:28)
```

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
