### ISSUE TITLE
🐛 Bug Report: [BETA] QUEST Magical Pandemic

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1232]
### 👟 Reproduction steps

Try to start the Magical Pandemic quest by talking to Clarck

### 👍 Expected behavior

for quest to work 

### 👎 Actual Behavior

error!

### 💥 Error message

```
TypeError: Cannot read properties of undefined (reading 'fileName')
    at /bin/src/SlashCommands/Commands/Location/Talk.ts:623:45
    at Array.filter (<anonymous>)
    at TalkCommand.handleQuest (/bin/src/SlashCommands/Commands/Location/Talk.ts:623:5)
    at TalkCommand.prepareDialog (/bin/src/SlashCommands/Commands/Location/Talk.ts:833:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TalkCommand.run (/bin/src/SlashCommands/Commands/Location/Talk.ts:897:18)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:663:28)
```

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed.
