### ISSUE TITLE
🐛 Bug Report: [BETA] QUEST Mystic Gravestone (membership)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1234]
### 👟 Reproduction steps

Get to step
```
!====[Crusch Karsten (felix69)'s conversation]====!
+ Mortimer - Hello Crusch Karsten (felix69)! What can I do for you?
+ 1 - Nothing, I'm just in transit.
+ 2 - I'm currently searching for some work to earn some extra gold. Do you need anything?
!=================================================!
```
and answer with the 2nd option

### 👍 Expected behavior

for quest to proceed

### 👎 Actual Behavior

error

### 💥 Error message

```
DiscordRESTError [400]: Invalid Form Body
  components.0.components.0.options.1.label: Must be 100 or fewer in length.
Error: 
    at RequestHandler.request (/bin/rpgbot/node_modules/slash-create/lib/util/requestHandler.js:62:15)
    at CommandContext.sendFollowUp (/bin/rpgbot/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:122:56)
    at CommandContext.send (/bin/rpgbot/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:97:25)
    at MysticGravestone.optionDialog (/bin/src/Data/Quest/Quest.ts:288:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MysticGravestone.handleStage (/bin/src/Data/Quest/Quests/MysticGravestone.ts:49:25)
    at TalkCommand.handleQuest (/bin/src/SlashCommands/Commands/Location/Talk.ts:670:4)
    at TalkCommand.run (/bin/src/SlashCommands/Commands/Location/Talk.ts:897:18)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:663:28)
```

### 🎲 DRPG version

v4.18.3-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Fixed
