### ISSUE TITLE
🐛 Bug Report: [BETA] inv value

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1238]
### 👟 Reproduction steps

/inv value

### 👍 Expected behavior

for it not to error

### 👎 Actual Behavior

errors with error below,   (some item doesn't seem to have "cost" set to it, no idea what item)

### 💥 Error message

```
TypeError: Cannot read properties of undefined (reading 'cost')
    at Object.entries.reduce.itemCount (/bin/src/SlashCommands/Commands/User/Inventory.ts:185:13)
    at Array.reduce (<anonymous>)
    at InventoryCommand.calculateInventoryValue (/bin/src/SlashCommands/Commands/User/Inventory.ts:172:67)
    at InventoryCommand.run (/bin/src/SlashCommands/Commands/User/Inventory.ts:232:19)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:663:28)
```

### 🎲 DRPG version

v4.18.4-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
@Sven65 Is this fixed? It wasn't auto-closed.

**Comment by mount2010** [comment]
Reopen if this is still an issue
