### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by ShadowGaming100** [DiscordDungeons/Bugs#1246]
### 👟 Reproduction steps

#!plant check in Copperfall

### 👍 Expected behavior

Plant check 

### 👎 Actual Behavior

Error

### 💥 Error message

**Whoops. An error occured.**
To report it, go to the link in `#!bug`, or visit `#!serverinvite` for support.
```js
QueryFailedError: deadlock detected
    at QueryFailedError.TypeORMError [as constructor] (/bin/rpgbot/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/bin/rpgbot/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/bin/rpgbot/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### 🎲 DRPG version

4.17.21

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment]
Issue is a deadlock issue
Already reported over at #1136  + highly known issue that the devs are aware of (possibly fixed in the slash command update that should be out by september)

**Comment by mount2010** [comment]
@FelixArgyle 
Slash command update will probably not fix deadlock bugs as that is an ORM issue.
Mackan was looking into moving into a different ORM (Prisma), however it is a lot of work.
