### ISSUE TITLE
🐛 Bug Report: Talking to Theodora the Enchantress

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1252]
### 👟 Reproduction steps

When I try and talk to Theodora the Enchantress

### 👍 Expected behavior

It should take me to the drop down with which Gem's I want to select

### 👎 Actual Behavior

It throws an error

### 💥 Error message

Error: Fetch your original message or use deferred messages before registering components
    at ComponentContext.registerComponent (/bin/rpgbot/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:223:19)
    at /bin/src/Util/InteractionUtil/SelectionPager.ts:91:13
    at Array.forEach (<anonymous>)
    at SelectionPager.start (/bin/src/Util/InteractionUtil/SelectionPager.ts:90:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Enchant.selectItem (/bin/src/Data/Quest/Quests/Enchant.ts:508:28)
    at Enchant.enchantOption (/bin/src/Data/Quest/Quests/Enchant.ts:294:35)
    at Enchant.handleStage (/bin/src/Data/Quest/Quests/Enchant.ts:525:4)

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Weebs666** [comment]
Additional when I got through to the gemstone selector and picked Ruby it threw the following, 
Error: Fetch your original message or use deferred messages before registering components
    at ComponentContext.registerComponent (/bin/rpgbot/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:223:19)
    at /bin/src/Data/Quest/Quest.ts:305:8
    at new Promise (<anonymous>)
    at Enchant.optionDialog (/bin/src/Data/Quest/Quest.ts:304:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Enchant.enchantOption (/bin/src/Data/Quest/Quests/Enchant.ts:325:28)
    at Enchant.handleStage (/bin/src/Data/Quest/Quests/Enchant.ts:525:4)

**Comment by Sven65** [comment]
I'm unable to reproduce the issue. Please reopen if it still occurs.
