### ISSUE TITLE
🐛 Bug Report: Providing no Value returns error

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1263]
### 👟 Reproduction steps

/pet set option:Xp Rate

### 👍 Expected behavior

for it to require a value  / or respond back that you need to input a value

### 👎 Actual Behavior

errors

### 💥 Error message

```
RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values must be non-empty strings.
    at Function.verifyString (/bin/rpgbot/node_modules/discord.js/src/util/Util.js:427:41)
    at Function.normalizeField (/bin/rpgbot/node_modules/discord.js/src/structures/MessageEmbed.js:555:19)
    at /bin/rpgbot/node_modules/discord.js/src/structures/MessageEmbed.js:576:14
    at Array.map (<anonymous>)
    at Function.normalizeFields (/bin/rpgbot/node_modules/discord.js/src/structures/MessageEmbed.js:575:8)
    at MessageEmbed.addFields (/bin/rpgbot/node_modules/discord.js/src/structures/MessageEmbed.js:339:42)
    at MessageEmbed.addField (/bin/rpgbot/node_modules/discord.js/src/structures/MessageEmbed.js:330:17)
    at PetSet.sendPetSettings (/bin/src/SlashCommands/Commands/Pets/PetSet.ts:198:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PetSet.run (/bin/src/SlashCommands/Commands/Pets/PetSet.ts:221:33)
    at PetCommand.routeToSubcommands (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:53:10)
    at PetCommand.run (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:78:10)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:670:28)
```

### 🎲 DRPG version

v4.18.11

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
Unable to reproduce. If the issue still occurs, please re-open.
