### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by MaraGoose** [DiscordDungeons/Bugs#1264]
### 👟 Reproduction steps

Triggered when attempting to do command /inv value. Other commands related to inventory seem to work well.

### 👍 Expected behavior

It should have returned inventory value.

### 👎 Actual Behavior

Error message.

### 💥 Error message

```
TypeError: Cannot read properties of undefined (reading 'user')
    at InventoryCommand.run (/bin/src/SlashCommands/Commands/User/Inventory.ts:209:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:670:28)
```

### 🎲 DRPG version

v4.18.11

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment]
Fixed already over at #1257 just pending an update to the bot for the change to be in effect 👍
