### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by joewhi86** [DiscordDungeons/Bugs#1269]
### 👟 Reproduction steps

Quest: A Small Task - traveled to Maple Grove

/talk npc: Madeleine

!====[Joseph Whitehouse's conversation]====!
+ Madeleine - 'sup, Joseph Whitehouse?
+ 1 - How did you know my name?
+ 2 - Elizabeth said something about boots?
!==========================================!

Selected Option 2, and got This interaction failed error
![2022-10-15_161719](https://user-images.githubusercontent.com/78335017/196007901-0f5596d5-49f2-41ad-affe-612e5a609882.png)

### 👍 Expected behavior

Receive a response from Madeleine

### 👎 Actual Behavior

This interaction failed

### 💥 Error message

```
DiscordRESTError [404]: Unknown Webhook
Error: 
    at RequestHandler.request (/bin/rpgbot/node_modules/slash-create/lib/util/requestHandler.js:62:15)
    at ComponentContext.sendFollowUp (/bin/rpgbot/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:128:56)
    at ComponentContext.send (/bin/rpgbot/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:102:25)
    at ASmallTask.optionDialog (/bin/src/Data/Quest/Quest.ts:288:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ASmallTask.handleStage (/bin/src/Data/Quest/Quests/ASmallTask.ts:363:25)
    at TalkCommand.handleQuest (/bin/src/SlashCommands/Commands/Location/Talk.ts:646:6)
    at TalkCommand.run (/bin/src/SlashCommands/Commands/Location/Talk.ts:897:18)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:674:28)
```

### 🎲 DRPG version

v4.18.19

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Guessing it's related to the latency issue, but I don't know for sure.

**Comment by Sven65** [comment]
@mount2010 Is this related to not deferring a message?

**Comment by joewhi86** [comment]
I'm not sure, but I think this one was resolved the last time the bot was restarted. I'm not seeing it anymore so I will close this out.

Thank you!!
