### ISSUE TITLE
🐛 Bug Report: Error on action

### ISSUE THREAD

**Issue by Raptechs** [DiscordDungeons/Bugs#1282]
### 👟 Reproduction steps

When I try to forage I get this error.. I get slightly different errors for mining and chopping. It seems as though the action goes through because if I try to do it again, I get the stamina message.

I do not get an error if I fish and catch nothing.

### 👍 Expected behavior

I'd expect to see the results of the action.

### 👎 Actual Behavior

Gives me the provided error message.

### 💥 Error message

```
IllegalOperationError: Channel closed
    at Channel.<anonymous> (/bin/rpgbot/node_modules/amqplib/lib/channel.js:160:11)
    at Channel.C.publish (/bin/rpgbot/node_modules/amqplib/lib/channel_model.js:158:15)
    at RabbitMQ.sendMessage (/bin/src/Services/RabbitMQ.ts:125:17)
    at AchievementManager.checkAchievements (/bin/src/Util/AchievementManager.ts:187:44)
    at ForageCommand.run (/bin/src/SlashCommands/Commands/Sides/Forage.ts:234:3)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:674:28)
```

### 🎲 DRPG version

v4.18.23

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
Hello! Thanks for reporting this bug.
This appears to be a problem with our RabbitMQ service.
I haven't seen this error message before, so it might have to do with recent changes to our infrastructure.
@Sven65, do you know if RabbitMQ was impacted in the migration?

**Comment by Raptechs** [comment]
This appears to now be resolved. I get information back from actions now and not the error messages.

**Comment by mount2010** [comment]
@Sven65 mentioned this issue was because of a failure to reconnect to our RabbitMQ service. A bot restart fixes this problem, and this is apparently a rare issue. 

Closing.
