### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by Keyvonnn** [DiscordDungeons/Bugs#1283]
### 👟 Reproduction steps

just typing /forage

### 👍 Expected behavior

i thought i wouldve forage 

### 👎 Actual Behavior

it gave me a error message

### 💥 Error message

```
IllegalOperationError: Channel closed
    at Channel.<anonymous> (/bin/rpgbot/node_modules/amqplib/lib/channel.js:160:11)
    at Channel.C.publish (/bin/rpgbot/node_modules/amqplib/lib/channel_model.js:158:15)
    at RabbitMQ.sendMessage (/bin/src/Services/RabbitMQ.ts:125:17)
    at AchievementManager.checkAchievements (/bin/src/Util/AchievementManager.ts:187:44)
    at ForageCommand.run (/bin/src/SlashCommands/Commands/Sides/Forage.ts:234:3)
    at SlashCreator._runCommand (/bin/rpgbot/node_modules/slash-create/lib/creator.js:674:28)
```

### 🎲 DRPG version

v4.18.23

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment]
Has been reported via #1282
