### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by pjfry2184575** [DiscordDungeons/Bugs#1294]
### 👟 Reproduction steps

i went to Alex in Lemontree Plaza to accept a new task for the day.

+ Alex - Hello P.J. Fry, Madeleine says they want 4 Gauges.

After crafting the gauges I then headed to The Sick Dahlia thinking Madeleine was there but it was Mathilda.
So i headed to Maple Grove and sent the cmd to talk to Madeleine when i get the error message 

### 👍 Expected behavior

i should of received my daily lux 
 

### 👎 Actual Behavior

My gauges were taken and i have an ongoing task i cant complete and i did not received my 5 lux

### 💥 Error message

```
QueryFailedError: deadlock detected
    at QueryFailedError.TypeORMError [as constructor] (/bin/rpgbot/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/bin/rpgbot/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/bin/rpgbot/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### 🎲 DRPG version

v4.18.27

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
This issue has been fixed.
