### ISSUE TITLE
🐛 Bug Report: Error on /mine

### ISSUE THREAD

**Issue by Dx8pi** [DiscordDungeons/Bugs#1318]
### 👟 Reproduction steps

/mine

### 👍 Expected behavior

Show results

### 👎 Actual Behavior

Throws error

### 💥 Error message

```
QueryFailedError: deadlock detected
    at QueryFailedError.TypeORMError [as constructor] (/bin/rpgbot/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/bin/rpgbot/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/bin/rpgbot/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### 🎲 DRPG version

v4.18.34

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

I tried doing /mine again and I had a cd, no error this time, so I'm assuming it went through.

**Comment by Sven65** [comment]
Can't reproduce.
