### ISSUE TITLE
🐛 Bug Report: /forage command return error

### ISSUE THREAD

**Issue by timlidos** [DiscordDungeons/Bugs#1367]
### 👟 Reproduction steps

TypeError: Cannot read properties of undefined (reading 'minlevel')
    at /bin/src/SlashCommands/Commands/Sides/Forage.ts:117:51
    at Array.filter (<anonymous>)
    at ForageCommand.getItem (/bin/src/SlashCommands/Commands/Sides/Forage.ts:116:47)
    at ForageCommand.run (/bin/src/SlashCommands/Commands/Sides/Forage.ts:192:23)
    at originalCommandRunner (/bin/src/Bot.ts:117:18)

### 👍 Expected behavior

/forage command works.

### 👎 Actual Behavior

/forage command doesn't work.

### 💥 Error message

```
TypeError: Cannot read properties of undefined (reading 'minlevel')
    at /bin/src/SlashCommands/Commands/Sides/Forage.ts:117:51
    at Array.filter (<anonymous>)
    at ForageCommand.getItem (/bin/src/SlashCommands/Commands/Sides/Forage.ts:116:47)
    at ForageCommand.run (/bin/src/SlashCommands/Commands/Sides/Forage.ts:192:23)
    at originalCommandRunner (/bin/src/Bot.ts:117:18)
```

### 🎲 DRPG version

v4.18.42

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment]
This has been fixed. Was an issue with an items data.
