### ISSUE TITLE
🐛 Bug Report: Impossible Talk to Nanurjuk

### ISSUE THREAD

**Issue by AnaBeatrizdeMelloPereira** [DiscordDungeons/Bugs#1374]
### 👟 Reproduction steps

I'm doing the Exotic Eggnog quest and when I went to the tavern in Frostridge to talk to Nanurjuk this error happened, talking to other NPCs seems normal.

### 👍 Expected behavior

Well, I should at least be able to talk to him, right?

### 👎 Actual Behavior

The moment I did the \talk action the error appeared.
![image](https://github.com/DiscordDungeons/Bugs/assets/127670397/97504d8b-7540-4b6e-9164-1a8ac5da03f4)
![Screenshot_1](https://github.com/DiscordDungeons/Bugs/assets/127670397/4151696a-e39c-4adc-95bf-3c790bd76e08)

### 💥 Error message

```
DiscordRESTError [400]: Invalid Form Body
  components.0.components.0.emoji.name: Invalid emoji
Error: 
    at RequestHandler.request (/bin/rpgbot/node_modules/slash-create/lib/util/requestHandler.js:62:15)
    at CommandContext.edit (/bin/rpgbot/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:145:56)
    at CommandContext.editOriginal (/bin/rpgbot/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:162:36)
    at CommandContext.send (/bin/rpgbot/node_modules/slash-create/lib/structures/interfaces/messageInteraction.js:83:25)
    at ExoticEggnog.continueCheckMessage (/bin/src/Data/Quest/Quest.ts:487:40)
    at ExoticEggnog.continueCheckDialog (/bin/src/Data/Quest/Quest.ts:440:15)
    at ExoticEggnog.handleStage (/bin/src/Data/Quest/Quests/ExoticEggnog.ts:129:36)
    at ExoticEggnog.prepareStage (/bin/src/Data/Quest/Quest.ts:532:15)
    at TalkCommand.handleQuest (/bin/src/SlashCommands/Commands/Location/Talk.ts:715:25)
    at TalkCommand.prepareDialog (/bin/src/SlashCommands/Commands/Location/Talk.ts:907:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TalkCommand.run (/bin/src/SlashCommands/Commands/Location/Talk.ts:973:18)
    at originalCommandRunner (/bin/src/Bot.ts:121:18)
```

### 🎲 DRPG version

v4.18.48

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

It's been a while since I've touched the bot, so I don't remember how to complete the quest, I saw on the wiki that I should talk to the NPC in question to advance.

**Comment by Sven65** [comment]
Fixed in same fix for #1371
