### ISSUE TITLE
🐛 Bug Report: Guild Display and Image 

### ISSUE THREAD

**Issue by PJFry8338** [DiscordDungeons/Bugs#1375]
### 👟 Reproduction steps

I change my guild display to modern, image type to full image, and then tried to add an image.

Something went wrong while adding the image link 

### 👍 Expected behavior

Should of opened the guild info menu

### 👎 Actual Behavior

Gave me a error message & now am locked out editing my guild 

### 💥 Error message

```
Error: Received one or more errors
    at UnionValidator.handle (/bin/rpgbot/node_modules/@sapphire/shapeshift/src/validators/UnionValidator.ts:105:14)
    at UnionValidator.parse (/bin/rpgbot/node_modules/@sapphire/shapeshift/src/validators/BaseValidator.ts:103:2)
    at EmbedBuilder.setDescription (/bin/rpgbot/node_modules/@discordjs/builders/src/messages/embed/Embed.ts:223:24)
    at getGuildEmbed (/bin/src/Util/GuildUtils.ts:98:4)
    at GInfoCommand.sendGuildInfo (/bin/src/SlashCommands/Commands/Guild/GCommand/GInfo.ts:406:18)
    at GInfoCommand.run (/bin/src/SlashCommands/Commands/Guild/GCommand/GInfo.ts:1123:3)
    at GuildCommand.routeToSubcommands (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:53:10)
    at GuildCommand.run (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:78:10)
    at originalCommandRunner (/bin/src/Bot.ts:121:18)
```

### 🎲 DRPG version

v4.18.48

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by GottZ** [comment]
```json
{
  "allies": [],
  "channel": "",
  "deaths": 0,
  "desc": "",
  "display": 2,
  "elder": [],
  "gold": 20717090,
  "icon": "😶‍🌫️",
  "icons": [
    "😶‍🌫️",
    "😶‍🌫️"
  ],
  "id": "f3b736ec-f9ed-421a-a477-423b95e9cbc3",
  "image": {
    "type": 2,
    "url": "https://gyazo.com/2a274b58c6e2ea18183764ca4d1df01f.png"
  },
  "inv": {
    "1": 1,
    "10": 2,
    "12": 1
  },
  "invites": [],
  "level": 1,
  "levelreq": 0,
  "loweredName": "secret stash",
  "max": 50,
  "members": [
    "1235135453179547750",
    "1236086956987777034"
  ],
  "name": "Secret Stash",
  "open": false,
  "owner": "1235135453179547750",
  "permissions": {},
  "role": "",
  "slain": 0,
  "uinv": {}
}
```

cc @Sven65
issue still present.
https://discord.com/channels/172382467385196544/172388244007288832/1261473821936844882

**Comment by Sven65** [comment]
Fixed
