### ISSUE TITLE
🐛 Bug Report: uset set nick

### ISSUE THREAD

**Issue by PJFry8338** [DiscordDungeons/Bugs#1377]
### 👟 Reproduction steps

Changed my nick display to option 3 

### 👍 Expected behavior

Should of changed the style of my name

### 👎 Actual Behavior

Produced an error message 

### 💥 Error message

```
DiscordAPIError[10013]: Unknown User
    at handleErrors (/bin/rpgbot/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at SequentialHandler.runRequest (/bin/rpgbot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:398:20)
    at SequentialHandler.queueRequest (/bin/rpgbot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:168:11)
    at _REST.request (/bin/rpgbot/node_modules/@discordjs/rest/src/lib/REST.ts:211:20)
    at GuildMemberManager._fetchSingle (/bin/rpgbot/node_modules/discord.js/src/managers/GuildMemberManager.js:221:18)
    at setNick (/bin/src/Util/Common.ts:46:20)
    at UsetCommand.setUserData (/bin/src/SlashCommands/Commands/User/Uset.ts:228:5)
    at UsetCommand.run (/bin/src/SlashCommands/Commands/User/Uset.ts:438:4)
    at originalCommandRunner (/bin/src/Bot.ts:121:18)
```

### 🎲 DRPG version

v4.18.49

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by PJFry8338** [comment]
I am the server owner, so that may actually be the issue since it can't change my name, but instead of the error message it should give some sort of warning that it can't change the owners nick

**Comment by GoldenFurredFox** [comment]
Got the same error in the official DRPG server when trying to set to 2 instead of 3. I think the bot doesn't understand that the discriminator isn't a thing anymore since it hasn't gotten an update in a hot second. The reason why I'm guessing that is at the end of the first line, which says "Unknown User".
