### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by PJFry8338** [DiscordDungeons/Bugs#1378]
### 👟 Reproduction steps

When I send `/g info` I get this error 

### 👍 Expected behavior

It should of sent my guild info 

### 👎 Actual Behavior

Was given this error

### 💥 Error message

```
Error: Received one or more errors
    at UnionValidator.handle (/bin/rpgbot/node_modules/@sapphire/shapeshift/src/validators/UnionValidator.ts:105:14)
    at UnionValidator.parse (/bin/rpgbot/node_modules/@sapphire/shapeshift/src/validators/BaseValidator.ts:103:2)
    at EmbedBuilder.setDescription (/bin/rpgbot/node_modules/@discordjs/builders/src/messages/embed/Embed.ts:223:24)
    at getGuildEmbed (/bin/src/Util/GuildUtils.ts:98:4)
    at GInfoCommand.sendGuildInfo (/bin/src/SlashCommands/Commands/Guild/GCommand/GInfo.ts:406:18)
    at GInfoCommand.run (/bin/src/SlashCommands/Commands/Guild/GCommand/GInfo.ts:1125:3)
    at GuildCommand.routeToSubcommands (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:53:10)
    at GuildCommand.run (/bin/src/SlashCommands/ParentCommands/BaseSlashCommand.ts:78:10)
    at originalCommandRunner (/bin/src/Bot.ts:121:18)
```

### 🎲 DRPG version

v4.18.49

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by GottZ** [comment]
same as #1375
