### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by PJFry8338** [DiscordDungeons/Bugs#1379]
### 👟 Reproduction steps

I sent `/give user:userId what:Gold quantity:10000 ` and was given the error message 

### 👍 Expected behavior

To send the user 10,000 Gold

### 👎 Actual Behavior

Received the error message 

### 💥 Error message

```
DiscordAPIError[50001]: Missing Access
    at handleErrors (/bin/rpgbot/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at SequentialHandler.runRequest (/bin/rpgbot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:398:20)
    at SequentialHandler.queueRequest (/bin/rpgbot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:168:11)
    at _REST.request (/bin/rpgbot/node_modules/@discordjs/rest/src/lib/REST.ts:211:20)
    at ChannelManager.fetch (/bin/rpgbot/node_modules/discord.js/src/managers/ChannelManager.js:123:18)
    at fetchDiscordChannelById (/bin/src/Util/Utils.ts:11:9)
    at GiveCommand.run (/bin/src/SlashCommands/Commands/User/Give.ts:276:14)
    at originalCommandRunner (/bin/src/Bot.ts:121:18)
```

### 🎲 DRPG version

v4.18.49

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

This is with any item I try to send
Mainly starter items

**Comment by Sven65** [comment]
Fixed.
