### ISSUE TITLE
Suggestion error

### ISSUE THREAD

**Issue by vinhloc30796** [DiscordDungeons/Bugs#163]
![image](https://cloud.githubusercontent.com/assets/19675202/25997389/7a2fad6e-3724-11e7-97f6-57bb9a1aed9f.png)

**Comment by PlayTheFallen** [comment]
@vinhloc30796 have you tried without the speech marks?
https://this.is-real.life/ab9ca8.png
https://this.is-real.life/e283cf.png

**Comment by vinhloc30796** [comment]
Yes I did, even before this actually. I should have included that as a picture too.
![image](https://cloud.githubusercontent.com/assets/19675202/26021032/4a0a4a48-378f-11e7-8012-afd46f58e268.png)

Here's the error message just in case you need it.
```javascript
TypeError: Cannot read property 'name' of null
    at Object.Execute (/home/mackan/RPGBot/src/Commands/general/suggest.js:8:208)
    at User.setFirstTime.then.then (/home/mackan/RPGBot/src/Handlers/messageCreate.js:149:56)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by SnazzyPine25** [comment]
Old issue and has been fixed.
