### ISSUE TITLE
Setting a guild's tag results in an error

### ISSUE THREAD

**Issue by bubbie** [DiscordDungeons/Bugs#181]
When changing a guild's tag, I got an error saying that Guild.setTag is not a function.
It still took my Guild Tag out of the guild's inventory.
https://hack-my-mainfra.me/e553a2.png

```TypeError: Guild.setTag is not a function
    at guildInv.removeItems.then (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gset.js:133:18)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

**Comment by bubbie** [comment]
I'd also like it if I can have my Guild Tag refunded
Discord ID 213621714909659136, tag bubbie#1380

**Comment by Maxxxel** [comment]
Got same issue
