### ISSUE TITLE
An issue while joining guilds (#!gjoin)

### ISSUE THREAD

**Issue by NikoMasumi** [DiscordDungeons/Bugs#217]
Quick bug report >.>
I've seen a member doing `#!gjoin Rogue Revolution`, and it throws an error.

```js
TypeError: Cannot read property 'length' of undefined
    at Gjoin.checkIfUserCanJoin (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gjoin.js:119:23)
    at Gjoin.joinGuild (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gjoin.js:98:24)
    at guildGlobs.getAll.then.guilds (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gjoin.js:176:11)
```

Thanks if you could fix this as soon as possible!

**Comment by Sven65** [comment]
Can't reproduce.
