### ISSUE TITLE
Error with #!adv cooldown.

### ISSUE THREAD

**Issue by Naoeaoe** [DiscordDungeons/Bugs#223]
`TypeError: Cannot read property 'setColor' of null
    at server.getPrefix.then (/home/mackan/RPGBot/src/Commands/Commands/Adventure/Adventure.js:233:19)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)`

**Comment by HustlePuff** [comment]
should be fixed now

**Comment by Sven65** [comment]
This isn't even the cooldown, and it is fixed
