### ISSUE TITLE
bug gmbuy

### ISSUE THREAD

**Issue by Groudon383** [DiscordDungeons/Bugs#258]
Hello, a bug was due to the fact that I bought coal. Screen offer:
[1](http://savepic.net/9551310.htm)
[2](http://savepic.net/9535950.htm)

error:

TypeError: Cannot read property 'item' of undefined
    at Gmbuy.getTradeInfo (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmbuy.js:18:44)
    at message.client.cache.hgetAll.then.redisData (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmbuy.js:108:29)
    at process._tickCallback (internal/process/next_tick.js:109:7)

o.o

**Comment by SnazzyPine25** [comment]
Can confirm.
