### ISSUE TITLE
Battles Has An ERRor

### ISSUE THREAD

**Issue by RedbearPlayz** [DiscordDungeons/Bugs#270]
TypeError: Cannot read property 'pvp' of null
    at Battle.checkHinders (/home/mackan/RPGBot/src/Commands/Commands/Battles/Battle.js:29:17)
    at toUser.get.then.toUserData (/home/mackan/RPGBot/src/Commands/Commands/Battles/Battle.js:58:33)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by TheBaconSpace** [comment]
Got Same issue `TypeError: Cannot read property 'pvp' of null
    at Battle.checkHinders (/home/mackan/RPGBot/src/Commands/Commands/Battles/Battle.js:29:17)
    at toUser.get.then.toUserData (/home/mackan/RPGBot/src/Commands/Commands/Battles/Battle.js:58:33)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)`

**Comment by Sven65** [comment]
How old are your drpg accounts? It might be that your userdata formats are too old.

**Comment by Sven65** [comment]
No info given, closing.

**Comment by TheBaconSpace** [comment]
@Sven65 how can i Check how old is my rpg account?
