### ISSUE TITLE
Bug with attribute scrolls

### ISSUE THREAD

**Issue by Twind1** [DiscordDungeons/Bugs#287]
#!use attribute scroll

DiscordRPGBOT - Today at 4:34 PM
Whoops. An error occured. Please report this in the official server.

TypeError: data.userClass.setAttributes is not a function
    at userInv.removeItems.then (/home/mackan/RPGBot/src/Commands/Commands/User/Use.js:223:28)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by Sven65** [comment]
Fixed.
