### ISSUE TITLE
Air Key error

### ISSUE THREAD

**Issue by bookworm5** [DiscordDungeons/Bugs#290]
As of 8/22/2017, trying to use an air key gives me this error
Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'charisma' of null
    at userInv.removeItems.then.then.then.items (/home/mackan/RPGBot/src/Commands/Commands/User/Use.js:247:71)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

However, the air key is used up and the number of chests I have decreases by one if I look afterwards.

**Comment by Sven65** [comment]
Fixed
