### ISSUE TITLE
#!heal auto 

### ISSUE THREAD

**Issue by MidgardEmber** [DiscordDungeons/Bugs#303]
[9ROE] Midgard Ember [Lvl. 9] - Today at 4:55 PM
#!heal auto
DiscordRPGBOT - Today at 4:55 PM
Whoops. An error occured. Please report this in the official server.
ReqlDriverCompileError: Argument 1 to get may not be `undefined`.
    at ReqlDriverCompileError.ReqlError [as constructor] (/home/mackan/RPGBot/node_modules/rethinkdb/errors.js:23:13)
    at ReqlDriverCompileError.ReqlCompileError [as constructor] (/home/mackan/RPGBot/node_modules/rethinkdb/errors.js:35:51)
    at new ReqlDriverCompileError (/home/mackan/RPGBot/node_modules/rethinkdb/errors.js:46:57)
    at Get.<anonymous> (/home/mackan/RPGBot/node_modules/rethinkdb/ast.js:1462:17)
    at Get.RDBOp [as constructor] (/home/mackan/RPGBot/node_modules/rethinkdb/ast.js:1466:8)
    at new Get (/home/mackan/RPGBot/node_modules/rethinkdb/ast.js:1846:38)
    at /home/mackan/RPGBot/node_modules/rethinkdb/ast.js:1068:43
    at Function.RDBVal.get (/home/mackan/RPGBot/node_modules/rethinkdb/ast.js:1070:7)
    at Party.getParty (/home/mackan/RPGBot/src/Classes/Party/Party.js:32:32)
    at user.addHp.then.then (/home/mackan/RPGBot/src/Commands/Commands/User/Heal.js:101:19)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)

**Comment by Sven65** [comment]
Fixed.
