### ISSUE TITLE
#!catch causes bot to fail

### ISSUE THREAD

**Issue by Urbane360** [DiscordDungeons/Bugs#33]
A player was attampting to #!catch a Monster, and it 'seemed' it was successfull, however it caused an error and the bot to fail completely. i.e. unable to perform any commands thereafter. Dialogue below:

**PLAYER 1 - Today at 11:02 AM**
#! catch
!catch

**PLAYER 2 - Today at 11:02 AM**
#!adv 2

**PLAYER 1- Today at 11:02 AM**
#!catch

**DiscordRPGBOT - Today at 11:02 AM**
Whoops. An error occured. Please report this in the official server.

TypeError: Cannot read property 'getLastExecTime' of undefined
    at Data.server.getPrefix.then.e (/root/RPGBot/main.js:217:21)

Whoops. An error occured. Please report this in the official server.

TypeError: Cannot read property 'getLastExecTime' of undefined
    at Data.server.getPrefix.then.e (/root/RPGBot/main.js:217:21)

**PLAYER 2 - Today at 11:03 AM**
o_o

**PLAYER 1 - Today at 11:03 AM**
#!adv 2

**DiscordRPGBOT - Today at 11:03 AM**
Whoops. An error occured. Please report this in the official server.

TypeError: Cannot read property 'getLastExecTime' of undefined
    at Data.server.getPrefix.then.e (/root/RPGBot/main.js:217:21)

**PLAYER 2 - Today at 11:03 AM**
#!stats @BookD20

**DiscordRPGBOT - Today at 11:03 AM**
Whoops. An error occured. Please report this in the official server.

TypeError: Cannot read property 'getLastExecTime' of undefined
    at Data.server.getPrefix.then.e (/root/RPGBot/main.js:217:21)

**PLAYER 2 - Today at 11:03 AM**
#!adv 2

**PLAYER 1 - Today at 11:03 AM**
#!pets
#!pet

**PLAYER 1 - Today at 11:04 AM**
#!adv 2

**DiscordRPGBOT - Today at 11:04 AM**
Whoops. An error occured. Please report this in the official server.

TypeError: Data.cooldown.getLastExecTime is not a function
    at Data.server.getPrefix.then.e (/root/RPGBot/main.js:217:22)

**Just Tomi [MC Advisor] - Today at 11:05 AM**
#!bug

DiscordRPGBOT - Today at 11:05 AM
To report a bug, please go to https://github.com/DiscordDungeons/Bugs/issues, thanks.
Whoops. An error occured. Please report this in the official server.

ReferenceError: firstTime is not defined
    at Data.cooldown.getLastExec.then (/root/RPGBot/main.js:221:12)
    at tryCatcher (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

**Comment by Sven65** [comment]
This was during a small issue with the bot due to a minor fix in the core.
The bug has been resolved.
