### ISSUE TITLE
An error when challenging another player to a battle

### ISSUE THREAD

**Issue by Harsh-man** [DiscordDungeons/Bugs#338]
It said to report it, so here it is:

Whoops. An error occured. Please report this in the official server.

```
TypeError: Cannot read property 'pvp' of null
    at Battle.checkHinders (/home/mackan/RPGBot/src/Commands/Commands/Battles/Battle.js:29:17)
    at toUser.get.then.toUserData (/home/mackan/RPGBot/src/Commands/Commands/Battles/Battle.js:58:33)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

Screenshot: 
![image](https://user-images.githubusercontent.com/31871124/30507752-4184964a-9a4e-11e7-8573-bf9f53b91f75.png)

**Comment by PlayTheFallen** [comment]
Your opponent hasn't created their profile.
