### ISSUE TITLE
market is broekn

### ISSUE THREAD

**Issue by nathanielcwm** [DiscordDungeons/Bugs#341]
Whoops. An error occured. Please report this in the official server.
```js
ReferenceError: User is not defined
    at Gmsearch.Execute (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmsearch.js:128:16)
    at client.cache.hset.then (/home/mackan/RPGBot/src/Handlers/messageCreate.js:147:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
that happens if u do gmsearch

**Comment by Sven65** [comment]
Fixed.
