### ISSUE TITLE
Problems when trying to battle someone

### ISSUE THREAD

**Issue by SebasTheNinja** [DiscordDungeons/Bugs#345]
I tried to battle someone and it told me that i need to enable battles first (which is weird because i could use it without problems a few days ago) and then the bot showed me this error.
```js
TypeError: Cannot read property 'pvp' of null
    at Battle.checkHinders (/home/mackan/RPGBot/src/Commands/Commands/Battles/Battle.js:29:17)
    at toUser.get.then.toUserData (/home/mackan/RPGBot/src/Commands/Commands/Battles/Battle.js:58:33)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```
![image](https://user-images.githubusercontent.com/32151264/30676133-dbae184e-9e5a-11e7-95ea-8323cb095dab.png)
**`EDIT`**
**Date:** 27/09/2017 
**Editor:** @PlayTheFallen
**Reason:** Formatted error to show as code block.

**Comment by PlayTheFallen** [comment]
What commands were run when this happened?

**Comment by Sven65** [comment]
Most likely battle, as seen in the error message

**Comment by PlayTheFallen** [comment]
@SebasTheNinja Your opponents data is registered as null.
*and they hadn't run the stats command before then*

**Comment by Sven65** [comment]
Fixed.
