### ISSUE TITLE
talking to pope seth in Temple of MOUKN return error

### ISSUE THREAD

**Issue by pin-dev** [DiscordDungeons/Bugs#356]
DiscordAPIError: Missing Access
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:68:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:183:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by PlayTheFallen** [comment]
DiscordRPG is missing reaction permissions on that server.
