### ISSUE TITLE
.use pickaxe returns error

### ISSUE THREAD

**Issue by ajstri** [DiscordDungeons/Bugs#383]
**Please describe your issue below.**  
Unable to equip pickaxe using `.use pickaxe`

**If an error is provided, please copy the block into the space below.**

```js

TypeError: Cannot read property 'then' of null
    at Use.useTool (/home/mackan/RPGBot/src/Commands/Commands/User/Use.js:390:7)
    at Use.item.get.then.itemData (/home/mackan/RPGBot/src/Commands/Commands/User/Use.js:448:13)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

```
[](https://media.discordapp.net/attachments/368064855371939841/369475419201601546/Screen_Shot_2017-10-16_at_9.22.54_AM.png?width=760&height=500)

**Comment by ajstri** [comment]
![screen shot 2017-10-16 at 9 22 54 am](https://user-images.githubusercontent.com/23582191/31614257-be83e962-b253-11e7-87f2-8ccf20d32165.png)

**Comment by Sven65** [comment]
Fixed.
