### ISSUE TITLE
Spooktober Spectacle Quest - on outside server

### ISSUE THREAD

**Issue by BADEVILEVIL** [DiscordDungeons/Bugs#389]
**Please describe your issue below.**  

[8:45 AM] BOTDiscordRPG: BADEVIL has arrived to Black Hallows Graveyard!
[8:45 AM] BADEVIL: #!talk wendell
[8:45 AM] BOTDiscordRPG: 
!====[BADEVIL's conversation]====!
+ Wendell - Great! Now I need you to bring those items to Scarlett at the temple.
!================================!

**If an error is provided, please copy the block into the space below.**

```js

< [8:45 AM] BOTDiscordRPG: Whoops. An error occured. Please report this in the official server.
DiscordAPIError: Missing Access
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:68:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:183:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < https://imgur.com/a/nnAc5 > )

**Comment by BADEVILEVIL** [comment]
This quest fork fine on official DD server:

[10:22 AM] BADEVIL: #!talk wendell
[10:22 AM] BOTSpookordRPG: 
!====[BADEVIL's conversation]====!
+ Wendell - Great! Now I need you to bring those items to Scarlett at the temple.
!================================!
🆗2
[10:22 AM] BOTSpookordRPG: Quest Updated - Travel to the Temple of MOUKN

**Comment by nathanielcwm** [comment]
@BADEVILEVIL try it again on ur server most likely a temporary bug stuff like that happens all the time

**Comment by BADEVILEVIL** [comment]
hmm ok I write that it work fine on official :-) made it 4 hours ago look last post before yours:-P
