### ISSUE TITLE
Gmsell bug

### ISSUE THREAD

**Issue by SebasTheNinja** [DiscordDungeons/Bugs#390]
**Please describe your issue below.**  
When i try to sell an item in the market with /gmsell  (Example: /gmsell Logs 6 10) it appears this error

**If an error is provided, please copy the block into the space below.**

```js

< error here >

TypeError: Cannot read property 'name' of undefined
    at results.results.map.hit (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmsell.js:69:62)
    at Array.map (<anonymous>)
    at Gmsell.checkResults (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmsell.js:69:20)
    at searchItem.then.results (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmsell.js:154:37)
    at <anonymous>

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

http://prntscr.com/gyqkyp

**Comment by Sven65** [comment]
Will look into

**Comment by Sven65** [comment]
Fixed.
