### ISSUE TITLE
gmselling for Grape

### ISSUE THREAD

**Issue by Teemine** [DiscordDungeons/Bugs#401]
**Please describe your issue below.** 

I was trying to gmsell a grape. And this came up. 

**If an error is provided, please copy the block into the space below.**

```js

< Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'name' of undefined
    at results.results.map.hit (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmsell.js:69:62)
    at Array.map (<anonymous>)
    at Gmsell.checkResults (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmsell.js:69:20)
    at searchItem.then.results (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmsell.js:154:37)
    at <anonymous> >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![Teemine - Today at 5:38 PM
#!gmsell grape 8 30
DiscordRPGBOT - Today at 5:38 PM
Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'name' of undefined
    at results.results.map.hit (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmsell.js:69:62)
    at Array.map (<anonymous>)
    at Gmsell.checkResults (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmsell.js:69:20)
    at searchItem.then.results (/home/mackan/RPGBot/src/Commands/Commands/Market/Gmsell.js:154:37)
    at <anonymous>]( < image url > )

**Comment by Sven65** [comment]
This is because it can't find the item "grape" as it's called "grapes", will fix.
