### ISSUE TITLE
#!use key

### ISSUE THREAD

**Issue by Superderpaherp** [DiscordDungeons/Bugs#44]
After using a key to attempt to open a chest this occurred. I also lost the key which I would like back.

TypeError: Cannot read property 'plural' of null
    at Data.user.inv.addItems.then (/root/RPGBot/cmds/user.js:325:188)
    at tryCatcher (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

**Comment by Sven65** [comment]
Fixed.
