### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FlashWhite** [DiscordDungeons/Bugs#444]
Put in #!search but came up with this error afterwards.

```js

< Error: connect ETIMEDOUT 104.16.58.5:443
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)>

```
![screenshot](https://user-images.githubusercontent.com/1161526/32869180-7b14e82c-ca2a-11e7-99c7-7acc9a060c16.png> )

**Comment by Sven65** [comment]
Discord issue.
