### ISSUE TITLE
Error while Traveling to Island of Desolation

### ISSUE THREAD

**Issue by Nightmare2112** [DiscordDungeons/Bugs#448]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

<DiscordRPGBOT - Today at 6:10 PM
Travel to Island of Desolation is done by boat. The boat will cost 500 gold.
Do you want to travel?
Whoops. An error occured. Please report this in the official server.
DiscordAPIError: Missing Access
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:68:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:183:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Nightmare2112** [comment]
After speaking with members in support it seems this is given, due to server permissions with Emote.
