### ISSUE TITLE
My friend got this error when trying to assign points

### ISSUE THREAD

**Issue by Pineeappleeee** [DiscordDungeons/Bugs#455]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

Issue got when my friend tried to assign points with the #!assign command

**If an error is provided, please copy the block into the space below.**

```js

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Execute.user.get.then.userData (/home/mackan/RPGBot/src/Commands/Commands/User/Assign.js:116:16)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
What command did he use?
Like, not just `#!assign`, but the full line.

**Comment by Sven65** [comment]
No more info was provided.
