### ISSUE TITLE
Can't craft iron ingot

### ISSUE THREAD

**Issue by huniiii** [DiscordDungeons/Bugs#459]
When i did #!craft iron ingot 3, there was a error message

< TypeError: Cannot read property 'type' of undefined
    at craft.get.then.craftData (/home/mackan/RPGBot/src/Commands/Commands/User/Craft.js:131:32)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)>

```
<img width="696" alt="screen shot 2017-11-27 at 5 46 39 pm" src="https://user-images.githubusercontent.com/34025528/33260681-93d66028-d39b-11e7-81e6-7f1c1398afee.png">


**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Fixed.
