### ISSUE TITLE
Error when adding guild ally

### ISSUE THREAD

**Issue by Monikaaaaaaa** [DiscordDungeons/Bugs#461]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
As I try to add nova to my gally I get this issue now, this script is showing up
**If an error is provided, please copy the block into the space below.**

```js

< ```TypeError: Cannot read property 'then' of undefined
    at Gally.addAlly (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gally.js:61:45)
    at user.getUserGuild.then.guildData (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gally.js:228:13)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```
![screen shot 2017-11-28 at 13 51 46](https://user-images.githubusercontent.com/34003429/33323187-92791c72-d443-11e7-8541-ce1aba9237d3.png)

>**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*
>
>![]( < image url > )

**`EDIT`**  
**Author:** @PlayTheFallen  
**Time:** Tue, 28 Nov 2017 15:08:27 GMT  
**Reason:** Fixed github markdown.

**`EDIT`**  
**Author:** @Sven65
**Time:** Wed, 29 Nov 2017 14:49 GMT  
**Reason:** Changed title to be more descriptive

**Comment by Sven65** [comment]
Fixed.
