### ISSUE TITLE
#!Gally bug

### ISSUE THREAD

**Issue by Takashi-22812** [DiscordDungeons/Bugs#463]
MACKANNNNNNNNNNNNNNNNNNNNN AHHHHHHHHHHHHHH
```js 
TypeError: Cannot read property 'then' of undefined
    at Gally.addAlly (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gally.js:61:45)
    at user.getUserGuild.then.guildData (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gally.js:228:13)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by Takashi-22812** [comment]
__***Why didn't the js code block work***__

**Comment by Sven65** [comment]
Already reported in #461.
