### ISSUE TITLE
advent command giving an error when used

### ISSUE THREAD

**Issue by GamerzBeHatin** [DiscordDungeons/Bugs#467]
when i used the advent command, it didnt work at all, not displaying anything. using it again gave the cooldown message as if it worked and using it after cooldown displayed this error message

```js
ReferenceError: itemData is not defined
    at inventory.addItems.then.then.then (/home/mackan/RPGBot/src/Commands/Commands/Advent/Advent.js:101:51)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by Exportforce** [comment]
Having the same issue

> ReferenceError: itemData is not defined
    at inventory.addItems.then.then.then (/home/mackan/RPGBot/src/Commands/Commands/Advent/Advent.js:101:51)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
