### ISSUE TITLE
Advent error message, seems to work

### ISSUE THREAD

**Issue by AardWolf** [DiscordDungeons/Bugs#468]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

First time I run `advent` (which uses `\` on the server I play one) I get the below message. I do get my items. If I run the command after the cooldown it tells me what I would have gotten.

**If an error is provided, please copy the block into the space below.**

```js

ReferenceError: itemData is not defined
    at inventory.addItems.then.then.then (/home/mackan/RPGBot/src/Commands/Commands/Advent/Advent.js:101:51)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Literally the issue prior, #467. Please read the others before creating a new one
