### ISSUE TITLE
quests problem

### ISSUE THREAD

**Issue by sp3ck4** [DiscordDungeons/Bugs#491]
Can't start quests or view any topic quest related

DiscordAPIError: Missing Access
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:218:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)```

![image](https://user-images.githubusercontent.com/34484782/33896204-8d9bfc04-df62-11e7-8495-e100c5356da6.png)

**Comment by sweetbream** [comment]
having the same problem 


TypeError: message.client.hasEmbedPerms is not a function
at Quest._showCurrent (/home/mackan/RPGBot/src/Commands/Commands/User/Quest.js:123:37)
at Quest._sendMainOptions (/home/mackan/RPGBot/src/Commands/Commands/User/Quest.js:209:16)
at 
at process._tickCallback (internal/process/next_tick.js:188:7)

![zzzzzzzzzzz](https://user-images.githubusercontent.com/34491114/33908632-b3465cf6-df4e-11e7-8c75-de8a3f329c0f.JPG)

**Comment by LadyBrittany** [comment]
Also having the same problem

TypeError: message.client.hasEmbedPerms is not a function
    at Quest._showCurrent (/home/mackan/RPGBot/src/Commands/Commands/User/Quest.js:123:37)
    at Quest._sendMainOptions (/home/mackan/RPGBot/src/Commands/Commands/User/Quest.js:209:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Sven65** [comment]
Same issue as #490

**Comment by sp3ck4** [comment]
Now it is working... At least the response
![image](https://user-images.githubusercontent.com/34484782/33942209-7499421c-e015-11e7-807a-534429b330be.png)

**Comment by Sven65** [comment]
Yeah, I fixed it.
