### ISSUE TITLE
Guild ad bug

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#498]
Hmm, how can I describe what has happened? , best I can put it is that an error popped up whilst using `#!guild ad` , yes I have the perms to set an ad out, below is the error code.

```js

TypeError: Cannot read property 'length' of undefined
    at Guild._getTextBlock (/home/mackan/RPGBot/src/Commands/Commands/Guild/Guild.js:53:20)
    at Guild.Execute (/home/mackan/RPGBot/src/Commands/Commands/Guild/Guild.js:183:20)
    at <anonymous>

```

**Comment by Sven65** [comment]
It's `#!guildad` though, fixing this one though
