### ISSUE TITLE
#!buyfield gives error message with no response

### ISSUE THREAD

**Issue by holroy** [DiscordDungeons/Bugs#532]
The bot returns an error when the player does _not_ respond to the **_buyfield_** command.

```js
DiscordAPIError: Missing Permissions
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:218:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

![Buyfield command with response after 30 seconds]( https://cdn.discordapp.com/attachments/334426225793695744/398607668098629632/unknown.png)

**Comment by holroy** [comment]
I do believe my settings for the bot are correct, but it does seem to work in the official server. So I'm not a 100% confident on it.

**Comment by Sven65** [comment]
The issue is that the bot doesn't have the necessary permissions, I'll add a check for it.
