### ISSUE TITLE
When Completing Sides

### ISSUE THREAD

**Issue by Nightmare2112** [DiscordDungeons/Bugs#539]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

ReqlRuntimeError: Cannot convert `undefined` with r.expr()
    at Function.Term.run (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/term.js:43:17)
    at Inventory.addItems (/home/mackan/RPGBot/src/Classes/User/Inventory.js:139:66)
    at Fish.Execute (/home/mackan/RPGBot/src/Commands/Commands/Sides/Fish.js:267:17)
    at <anonymous>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by kilillka** [comment]
Same happened to me when fishing
Whoops. An error occured. Please report this in the official server.
```js
ReqlRuntimeError: Cannot convert `undefined` with r.expr()
    at Function.Term.run (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/term.js:43:17)
    at Inventory.addItems (/home/mackan/RPGBot/src/Classes/User/Inventory.js:139:66)
    at Fish.Execute (/home/mackan/RPGBot/src/Commands/Commands/Sides/Fish.js:267:17)
    at <anonymous>
```
