### ISSUE TITLE
Error i was told to report.

### ISSUE THREAD

**Issue by Moose42088** [DiscordDungeons/Bugs#540]
ReferenceError: r is not defined
    at Function.<anonymous> (/home/mackan/RPGBot/src/Classes/User/Inventory.js:178:24)
    at new Func (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/term.js:3053:19)
    at Function.Term.expr (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/term.js:2339:12)
    at Function.Term.replace (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/term.js:587:39)
    at Inventory.removeItems (/home/mackan/RPGBot/src/Classes/User/Inventory.js:174:56)
    at Pheal.Execute (/home/mackan/RPGBot/src/Commands/Commands/Pets/Pheal.js:101:18)
    at <anonymous>

I hope this helps.

**Comment by Sven65** [comment]
fixed
