### ISSUE TITLE
Error when using #!sell

### ISSUE THREAD

**Issue by Nightmare2112** [DiscordDungeons/Bugs#541]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

ReferenceError: r is not defined
    at Function.<anonymous> (/home/mackan/RPGBot/src/Classes/User/Inventory.js:178:24)
    at new Func (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/term.js:3053:19)
    at Function.Term.expr (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/term.js:2339:12)
    at Function.Term.replace (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/term.js:587:39)
    at Inventory.removeItems (/home/mackan/RPGBot/src/Classes/User/Inventory.js:174:56)
    at Sell._Sell (/home/mackan/RPGBot/src/Commands/Commands/User/Sell.js:90:25)
    at <anonymous>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Same error as #540
