### ISSUE TITLE
Debug Bug 

### ISSUE THREAD

**Issue by Nightmare2112** [DiscordDungeons/Bugs#543]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
When excuting #!debug

**If an error is provided, please copy the block into the space below.**

```js

< ReferenceError: r is not defined
    at Bstats.Execute (/home/mackan/RPGBot/src/Commands/Commands/Admin/Debug.js:25:114)
    at module.exports (/home/mackan/RPGBot/src/Handlers/messageCreate.js:181:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) >

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by Sven65** [comment]
Fixed
