### ISSUE TITLE
Connection Error (Potentially?)

### ISSUE THREAD

**Issue by TW-Dodger** [DiscordDungeons/Bugs#544]
DiscordRPG spit this error out on a few servers I'm on a little bit ago.

ReqlServerError: The connection was closed before the query could be completed.
    at /home/mackan/RPGBot/node_modules/rethinkdbdash/lib/connection.js:848:28
    at Object.loopKeys (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/helper.js:56:14)
    at Connection._flush (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/connection.js:846:10)
    at Socket.<anonymous> (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/connection.js:120:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:545:12)

**Comment by Sven65** [comment]
Fixed
