### ISSUE TITLE
erm config not defined

### ISSUE THREAD

**Issue by nathanielcwm** [DiscordDungeons/Bugs#549]
**Please describe your issue below.**  

Got it while errr running the help command

**If an error is provided, please copy the block into the space below.**

Whoops. An error occured. Please report this in the official server.
```js
ReferenceError: config is not defined
    at Help._getPrefix (/home/mackan/RPGBot/src/Commands/Commands/General/Help.js:34:23)
    at Help.Execute (/home/mackan/RPGBot/src/Commands/Commands/General/Help.js:50:27)
    at module.exports (/home/mackan/RPGBot/src/Handlers/messageCreate.js:179:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by shroomyun** [comment]
#!help broke 
![umjl56d](https://user-images.githubusercontent.com/33994869/34995005-31abc1a8-fb10-11e7-98f8-5935ea295bb6.jpg)
as well as #!boss 
![zwkq31u](https://user-images.githubusercontent.com/33994869/34995012-38ea6f8c-fb10-11e7-9b1a-43c639433485.jpg)

**Comment by nathanielcwm** [comment]
yep can confirm help doesn't work at all
