### ISSUE TITLE
Privilege is too low...

### ISSUE THREAD

**Issue by Takashi-22812** [DiscordDungeons/Bugs#557]
Mackan there's a LOT of errors recently. Good Luck 👍
```js
DiscordAPIError: Privilege is too low...
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:218:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by PlayTheFallen** [comment]
what command was run to generate this error?

**Comment by Apaxz** [comment]
**#!uset nick**

**Comment by PlayTheFallen** [comment]
The bot has permission to `MANAGE_NICKNAMES, but the author of the message has a higher role than the bot.

**Comment by PlayTheFallen** [comment]
Will look into possible fix.

**Comment by Sven65** [comment]
This has probably been fixed since the issue was opened.
