### ISSUE TITLE
Can't start quest

### ISSUE THREAD

**Issue by roboraptor3000** [DiscordDungeons/Bugs#586]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  
Speaking to Pope Seth gives me an error, as does attempting to view current quest

**If an error is provided, please copy the block into the space below.**

```js

DiscordAPIError: Missing Access
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:218:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by PlayTheFallen** [comment]
You either don't have `ADD_REACTIONS` or `MANAGE_MESSAGES`.
