### ISSUE TITLE
Dungeon error 

### ISSUE THREAD

**Issue by lightningAsura** [DiscordDungeons/Bugs#669]
When I try starting a new dungeon the following error massage appears and the dungeon entrance fee still gets taken 

```js

Whoops. An error occured. Please report this in the official server.
Error: spawn ENOMEM
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at exports.fork (child_process.js:99:10)
    at Dungeon._startDungeon (/home/mackan/RPGBot/src/Commands/Commands/Dungeons/Dungeon.js:935:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```
![](https://i.imgur.com/h8bvaNG.png)

**Comment by tyler489** [comment]
Happened to me but after attempting to dungeon resume 3 ot 4 times it let me in

**Comment by Sven65** [comment]
Reported in #662
