### ISSUE TITLE
Dungeon Error

### ISSUE THREAD

**Issue by skinblow** [DiscordDungeons/Bugs#670]
**Be sure to read [here](https://github.com/DiscordDungeons/Bugs/blob/master/FAQ.md) first.**

**Please describe your issue below.**  

issue and command dungeon resume

**If an error is provided, please copy the block into the space below.**

Error: spawn ENOMEM
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at exports.fork (child_process.js:99:10)
    at Dungeon._resumeDungeon (/home/mackan/RPGBot/src/Commands/Commands/Dungeons/Dungeon.js:849:24)
    at <anonymous>

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![image](https://user-images.githubusercontent.com/39228613/39962928-30b1282c-5634-11e8-85cd-2f2520820cc5.png)

**Comment by Sven65** [comment]
Reported in #669
