### ISSUE TITLE
Unable to advertising a guild...

### ISSUE THREAD

**Issue by DANVXT** [DiscordDungeons/Bugs#689]
This error keep preventing me from advertising my guild, it happens a week ago and it's still bugging out...

```js
DiscordAPIError: Unknown Message
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by PlayTheFallen** [comment]
Resolved in home server.
