### ISSUE TITLE
inventory bug

### ISSUE THREAD

**Issue by munkiii** [DiscordDungeons/Bugs#704]
when I did command to view inventory it said this:

DiscordAPIError: Missing Permissions
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

rather than showing me my inventory this hasn't occurred before now and it didn't do it to other users using the bot and checking their inventory

**Comment by ryudragon98** [comment]
give the manage message and add reaction perms.
