### ISSUE TITLE
uset nick doesn't Work

### ISSUE THREAD

**Issue by GomulPL** [DiscordDungeons/Bugs#714]
I tried use command "uset nick" and a saw this

Whoops. An error occured. Please report this in the official server.
DiscordAPIError: Missing Permissions
    at item.request.gen.end (/home/mackan/RPGBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/mackan/RPGBot/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ryudragon98** [comment]
The bot needs manage nicknames perm. And if you have a role higher than the bot or you are the owner of the server you did this in then the bot can not change your nick.
