### ISSUE TITLE
ReqlRuntimeError: Cannot convert `undefined

### ISSUE THREAD

**Issue by AchilleasAlvaroHysi** [DiscordDungeons/Bugs#777]
writing #!read Log after search 

```js
ReqlRuntimeError: Cannot convert `undefined` with r.expr()
    at Function.Term.run (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/term.js:43:17)
    at Book.get (/home/mackan/RPGBot/src/Classes/Misc/Book.js:9:70)
    at Read._Read (/home/mackan/RPGBot/src/Commands/Commands/Books/Read.js:129:29)
    at Read.Execute (/home/mackan/RPGBot/src/Commands/Commands/Books/Read.js:205:14)
    at <anonymous>
```

```js
TypeError: Cannot read property 'length' of undefined
    at Read._getPage (/home/mackan/RPGBot/src/Commands/Commands/Books/Read.js:97:90)
    at Read._Read (/home/mackan/RPGBot/src/Commands/Commands/Books/Read.js:132:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by PlayTheFallen** [comment]
[ADMIN] Please reopen the issue using one of the templates.

**Comment by PlayTheFallen** [comment]
Apparently someone wanted this...
