### ISSUE TITLE
Adding Gem socket error message 

### ISSUE THREAD

**Issue by Zarroc1** [DiscordDungeons/Bugs#780]
Whoops. An error occured. Please report this in the official server.
```js
Error: Failed to send message to master process.
    at Promise (/home/mackan/RPGBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:43:24)
    at Promise (<anonymous>)
    at ShardClientUtil.send (/home/mackan/RPGBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:39:12)
    at Promise (/home/mackan/RPGBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:88:12)
    at Promise (<anonymous>)
    at ShardClientUtil.broadcastEval (/home/mackan/RPGBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:80:12)
    at Function.refreshAll (/home/mackan/RPGBot/src/Classes/Item/Item.js:368:31)
    at Function.alterItem (/home/mackan/RPGBot/src/Classes/Item/MetaItem.js:211:14)
    at <anonymous>
```

**Comment by myrissa** [comment]
same it ate my gem too can i get another one plz mackan it was my only sapphire!
![image](https://user-images.githubusercontent.com/46257828/50545371-424d2a80-0bcf-11e9-8683-dd1de3edae92.png) 
![image](https://user-images.githubusercontent.com/46257828/50545374-74f72300-0bcf-11e9-83cf-b7407dbd127f.png)

Error: Failed to send message to master process.
    at Promise (/home/mackan/RPGBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:43:24)
    at Promise (<anonymous>)
    at ShardClientUtil.send (/home/mackan/RPGBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:39:12)
    at Promise (/home/mackan/RPGBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:88:12)
    at Promise (<anonymous>)
    at ShardClientUtil.broadcastEval (/home/mackan/RPGBot/node_modules/discord.js/src/sharding/ShardClientUtil.js:80:12)
    at Function.refreshAll (/home/mackan/RPGBot/src/Classes/Item/Item.js:368:31)
    at Function.alterItem (/home/mackan/RPGBot/src/Classes/Item/MetaItem.js:211:14)
    at <anonymous>

**Comment by Willard21** [comment]
This was just from the duplicated bot processes yesterday.
