### ISSUE TITLE
a bug happened while adving

### ISSUE THREAD

**Issue by MalekTHEghost** [DiscordDungeons/Bugs#787]
```js
ReqlServerError: The connection was closed before the query could be completed.
    at /home/mackan/RPGBot/node_modules/rethinkdbdash/lib/connection.js:848:28
    at Object.loopKeys (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/helper.js:56:14)
    at Connection._flush (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/connection.js:846:10)
    at Socket.<anonymous> (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/connection.js:120:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:545:12)
```

**Comment by PlayTheFallen** [comment]
Database connection closed, this is being looked at.
Thank you for notifying.

**Comment by Willard21** [comment]
I think it's just yearly hardware troubles. A quick search shows it happening a lot in January of 2018 as well. Not really anything we can fix within the bot I don't think (except maybe a friendlier error message). https://discordapp.com/channels/172382467385196544/172388282057883648/405181446261702667

**Comment by Willard21** [comment]
This should be resolved now :ok_hand:
