### ISSUE TITLE
Joining guild error (add role issue)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#796]
**Describe the bug**
Phoenix Heart is an old guild that **used** to have a guild role within the Discord Dungeons server, as there were too many roles in the main server causing us to clean inactive guild roles, Phoenix Heart was caught up with the clean and their guild role was removed, as far as I'm aware Mackan mentioned that he removed them having an active guild role from the database aswell as refunded the costs to all guilds that had their role removed,  not sure why this error will exist as their guild role should've been removed from the database 🤔 

**To Reproduce**
1. #!gjoin Phoenix Heart
2. You will see the error mentioned shown below.
```javascript
TypeError: Cannot read property 'length' of null
    at Gjoin._addRoles (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gjoin.js:87:12)
    at Gjoin._joinGuild (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gjoin.js:114:15)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Expected behavior**
I expect this error to not appear.
**Screenshots**
![4f0956](https://user-images.githubusercontent.com/12903523/51811515-9e9b8b00-22f0-11e9-8571-e0969f8870ef.png)

**Version**
DRPG Version 4.7.0

**Additional context**
Many guild roles were removed due to a clean that happened in the Discord Dungeon's server due to the server reaching the role capacity, so there'd be many other guilds that if you join this error may show.

**Comment by Willard21** [comment]
Looks like he must have set the roles to `null` in the database, but only checks for `undefined` in the code. Easy fix.
