### ISSUE TITLE
Can't talk...

### ISSUE THREAD

**Issue by Takashi-22812** [DiscordDungeons/Bugs#840]
**You can't talk to NPCs**
Something like this pops up when you do:

To reproduce, simply talk to an NPC (includes NPC shops and stuff too).
```js
SequelizeDatabaseError: function array_append_distinct(integer[], bigint) does not exist
    at Query.formatError (/home/mackan/RPGBot/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)
    at query.catch.err (/home/mackan/RPGBot/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/mackan/RPGBot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/mackan/RPGBot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/mackan/RPGBot/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/mackan/RPGBot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
```

**Comment by Sven65** [comment]
Fixed, was an issue with database types.
