### ISSUE TITLE
Embed 2 Broken For Nova Trap

### ISSUE THREAD

**Issue by Takashi-22812** [DiscordDungeons/Bugs#844]
If you do recipe or item on the Nova Trap while using embed 2, it gives this error:
```js
RangeError: RichEmbed field values may not be empty.
    at RichEmbed.addField (/home/mackan/RPGBot/node_modules/discord.js/src/structures/RichEmbed.js:166:34)
    at Item._addFields (/home/mackan/RPGBot/src/Commands/Commands/General/Item2.js:58:10)
    at Item.Execute (/home/mackan/RPGBot/src/Commands/Commands/General/Item2.js:314:16)
```
```js
RangeError: RichEmbed field values may not be empty.
    at RichEmbed.addField (/home/mackan/RPGBot/node_modules/discord.js/src/structures/RichEmbed.js:166:34)
    at Recipe.Execute (/home/mackan/RPGBot/src/Commands/Commands/General/Recipe.js:131:12)
```

**Comment by Willard21** [comment]
Missing Author variable it looks like

**Comment by Willard21** [comment]
Fixed
