### ISSUE TITLE
Battle bugs

### ISSUE THREAD

**Issue by FelixCATus** [DiscordDungeons/Bugs#86]
BCANCEL
```js
TypeError: Cannot read property 'from' of undefined
    at User.getBattle.then (/home/Mackan/RPGBot/src/Commands/battles/bcancel.js:20:18)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

BACCEPT
```js
TypeError: Cannot read property 'to' of undefined
    at User.getBattle.then (/home/Mackan/RPGBot/src/Commands/battles/baccept.js:20:19)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

BREFUSE
```js
TypeError: Cannot read property 'from' of undefined
    at User.getBattle.then (/home/Mackan/RPGBot/src/Commands/battles/brefuse.js:19:19)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

BDRAW
```js
ReqlDriverCompileError: Argument 1 to get may not be `undefined`.
    at ReqlDriverCompileError.ReqlError [as constructor] (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:23:13)
    at ReqlDriverCompileError.ReqlCompileError [as constructor] (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:35:51)
    at new ReqlDriverCompileError (/home/Mackan/RPGBot/node_modules/rethinkdb/errors.js:46:57)
    at Get.<anonymous> (/home/Mackan/RPGBot/node_modules/rethinkdb/ast.js:1462:17)
    at Get.RDBOp [as constructor] (/home/Mackan/RPGBot/node_modules/rethinkdb/ast.js:1466:8)
    at new Get (/home/Mackan/RPGBot/node_modules/rethinkdb/ast.js:1846:38)
    at /home/Mackan/RPGBot/node_modules/rethinkdb/ast.js:1068:43
    at Table.RDBVal.get (/home/Mackan/RPGBot/node_modules/rethinkdb/ast.js:1070:7)
    at Battle.setDraw (/home/Mackan/RPGBot/src/Classes/Battle/battle.js:104:38)
    at User.getBattle.then (/home/Mackan/RPGBot/src/Commands/battles/bdraw.js:21:12)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
```

**Comment by Sven65** [comment]
I edited your thing to have syntax highlighting and make it easier to read

**Comment by Sven65** [comment]
FIXED
