### ISSUE TITLE
!gset icon Not working

### ISSUE THREAD

**Issue by Alevard** [DiscordDungeons/Bugs#87]
Here's the error message I receive

ReferenceError: args is not defined
    at User.getUserGuild.then (/home/Mackan/RPGBot/src/Commands/guild/gset.js:25:33)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by Sven65** [comment]
Should be fixed

**Comment by Alevard** [comment]
Nope. 

ReferenceError: args is not defined
    at User.getUserGuild.then (/home/Mackan/RPGBot/src/Commands/guild/gset.js:25:33)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by Sven65** [comment]
try now?

**Comment by Alevard** [comment]
Works <3

**Comment by Sven65** [comment]
Cool
