### ISSUE TITLE
Gbselling gmsell trades throws errors.

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#873]
**Describe the bug**
Trying to do gbsell on a selling trade (so one where you're expected to do gmbuy) throws and error.
```js
TypeError: Cannot read property 'item' of undefined
    at Gbsell._getTradeInfo (/home/mackan/RPGBot/src/Commands/Commands/Market/Gbsell.js:18:44)
    at Gbsell.Execute (/home/mackan/RPGBot/src/Commands/Commands/Market/Gbsell.js:168:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
**Screenshots**
![image](https://user-images.githubusercontent.com/24826881/69431631-bcadfe00-0cfd-11ea-8a94-f1a8915eacc9.png)

**Additional context**
This was from last week (so before the update). Just found it doing a Discord search for errors.

**Comment by Sven65** [comment]
Fixed in some other patch.
