### ISSUE TITLE
Misc Bugs here

### ISSUE THREAD

**Issue by Rosenkreuz12** [DiscordDungeons/Bugs#88]
#!getrole
```js
TypeError: Classes.User.user is not a constructor
    at Object.Execute (/home/Mackan/RPGBot/src/Commands/guild/getrole.js:10:14)
    at User.isFirstTime.then (/home/Mackan/RPGBot/src/Handlers/messageCreate.js:130:54)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by Rosenkreuz12** [comment]
#!getchat
```
ReferenceError: Data is not defined
    at Execute.User.get.then (/home/Mackan/RPGBot/src/Commands/guild/getchat.js:20:7)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by Rosenkreuz12** [comment]
lead command still haven't able to accept mine, fish, forage, chop fields

**Comment by Rosenkreuz12** [comment]
#!gblist 2...
```
ReferenceError: args is not defined
    at Object.Execute (/home/Mackan/RPGBot/src/Commands/market/gblist.js:6:14)
    at User.isFirstTime.then (/home/Mackan/RPGBot/src/Handlers/messageCreate.js:130:54)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by Rosenkreuz12** [comment]
skills doesn't leveled up when reached the amount needed to lvl up

```
!======== [Raylo's skills] ========!
+ Chop Level 5 (205 / 600 XP)
+ Fish Level 1 (18 / 20 XP)
+ Forage Level 4 (197 / 200 XP)
+ Mine Level 4 (204 / 200 XP)
!==================================!
```
...i'm too lazy to screenshot

**Comment by Rosenkreuz12** [comment]
#!grole
...ReferenceError: args is not defined
    at ToUser.get.then (/home/Mackan/RPGBot/src/Commands/guild/grole.js:44:34)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
...

**Comment by Sven65** [comment]
Edited to have syntax highlighting
