### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by itzevxn** [DiscordDungeons/Bugs#926]
**Describe the bug**

Whoops. An error occured. Please report this in the official server.
```js
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home/mackan/RPGBot/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/home/mackan/RPGBot/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**To Reproduce**
1. Was just doing Adventure Command
2. Error Occured

**Comment by Sven65** [comment]
Please follow the full issue template next time you create an issue.
What version is the bug in?

**Comment by Sven65** [comment]
No info provided, closing.
