### ISSUE TITLE
Guild Regex Borked

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#967]
**Describe the bug**
Guilds regex is broken and shows incorrect guilds

**To Reproduce**
1. Do `#!guild shelter` or `#!guild nova` -- shows wrong guild

**Expected behavior**
To show correct guilds.

**Screenshots**

![](https://cdn.discordapp.com/attachments/554648354592653313/787717839200976916/image1.png)
![](https://cdn.discordapp.com/attachments/554648354592653313/787717838805663744/image0.png)
![](http://senpai.pls-fuck.me/6d4Mvve.png) is the guild it should be showing for shelter
---

Error:

```js
ReqlLogicError: Error in regexp (?i)><((((º> (portion (?i)><((((º>): missing ): (?i)><((((º> in:
r.table("guilds").filter(function(var_229) {
    return var_229("name").match("(?i)><((((º>")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}).nth(0).default(null)

    at Connection._processResponse (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/connection.js:395:15)
    at Socket.<anonymous> (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/connection.js:201:14)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[12:42 PM]
Whoops. An error occured. Please report this in the official server.
ReqlRuntimeError: Cannot convert undefined with r.expr() in:
r.table("users").get(undefined)("name").default(undefined)
                     ^^^^^^^^^

    at Function.Term.run (/home/mackan/RPGBot/node_modules/rethinkdbdash/lib/term.js:43:17)
    at User.getName (/home/mackan/RPGBot/src/Classes/User/User.js:139:86)
    at Guild.Execute (/home/mackan/RPGBot/src/Commands/Commands/Guild/Guild.js:170:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[12:42 PM]
Whoops. An error occured. Please report this in the official server.
TypeError: Cannot read property 'length' of undefined
    at Guild._getTextBlock (/home/mackan/RPGBot/src/Commands/Commands/Guild/Guild.js:53:21)
    at Guild.Execute (/home/mackan/RPGBot/src/Commands/Commands/Guild/Guild.js:179:20)
```

![](http://senpai.pls-fuck.me/8SpNENe.png) nomi stats doesn't show the correct guild name
> .¸¸.·´¯·.¸¸.·´¯·.¸><(((º>
is their actual guild name

**Version**
 4.15.4 

**Additional context**
- Mackan broke this one :eyes:

**Comment by Sven65** [comment]
Yeah this was fixed 👀
