### ISSUE TITLE
reset bug

### ISSUE THREAD

**Issue by jdude147** [DiscordDungeons/Bugs#98]
doing #!reset YES doesn't reset but displays this, not sure why just created a new player recently and wanted to reassign my points but am disappointed to find out I can't :/

> ReferenceError: d is not defined
    at Server.getPrefix.then (/home/Mackan/RPGBot/src/Commands/user/reset.js:13:19)
    at tryCatcher (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/Mackan/RPGBot/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by Sven65** [comment]
Fixed.
