### ISSUE TITLE
Can't rename the prefix or pet

### ISSUE THREAD

**Issue by itsmich2407** [DiscordDungeons/Bugs#997]
hello, I keep getting an error that doesn't allow me to rename the prefix or my pet. I follow the instructions as described and am certain I type it correctly.

this is for the pet rename error:
Whoops. An error occured. Please report this in the official server.
TypeError: this.replace is not a function
    at String.value (/home/mackan/RPGBot/src/Util/Extenders.js:11:20)
    at Pset.Execute (/home/mackan/RPGBot/src/Commands/Commands/Pets/Pset.js:214:13)

this is for the prefix error:
Whoops. An error occured. Please report this in the official server.
TypeError: this.replace is not a function
    at String.value (/home/mackan/RPGBot/src/Util/Extenders.js:11:20)
    at Setprefix.Execute (/home/mackan/RPGBot/src/Commands/Commands/Admin/Setprefix.js:26:15)
    at module.exports (/home/mackan/RPGBot/src/Handlers/messageCreate.js:225:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

DRPG Version 4.15.5 - Made by Mackan#7196

**Comment by Sven65** [comment]
Please follow the bug report template. It's there for a reason. Only having an error message, without any way of knowing how to actually reproduce it makes it very hard for us to fix the error.

If you create a new bug report, the template will be there for you to copy over to this one. Alternatively, you can create two new ones following it, one for the pet name issue, and one for the prefix issue.

Thanks.

**Comment by FelixArgyle** [comment]
I'll do it dw.

**Describe the bug**
Anything that has `this.replace` is broken, known things that have it are "Pset name`  and `setprefix`, just assume anything replacing a current string.

**To Reproduce**
Steps to reproduce the behavior:
1. do `#!pset name new-name` | `#!setprefix new-prefix`

4. See error
```
TypeError: this.replace is not a function
    at String.value (/home/mackan/RPGBot/src/Util/Extenders.js:11:20)
    at Pset.Execute (/home/mackan/RPGBot/src/Commands/Commands/Pets/Pset.js:214:13)
```
---
```
TypeError: this.replace is not a function
    at String.value (/home/mackan/RPGBot/src/Util/Extenders.js:11:20)
    at Setprefix.Execute (/home/mackan/RPGBot/src/Commands/Commands/Admin/Setprefix.js:26:15)
    at module.exports (/home/mackan/RPGBot/src/Handlers/messageCreate.js:225:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Expected behavior**
To not error + change the prefix / pet name (and any other thing that these errors may involve)

**Screenshots**
![screenshot1](http://senpai.pls-fuck.me/6PesuYm.jpg)
![screenshot2](http://senpai.pls-fuck.me/3Rq7Uf9.jpg)

**Version**
4.15.5

**Additional context**
Anything that has `this.replace` may be broken so best to check everything that has that used.

**Comment by itsmich2407** [comment]
@FelixArgyle Thank you so much for doing this, I honestly wasn't even sure what the error was saying.
